// ============================================================================
// INTENSIVE WORKFLOW TEMPLATES - PART 2: ADDITIONAL SPECIALTIES
// ============================================================================
// Continuation of intensive workflow templates with orthopedics, gastroenterology,
// nephrology, pulmonology, emergency medicine, and geriatrics specialties.
// ============================================================================

export const INTENSIVE_WORKFLOW_TEMPLATES_PT2 = [
  // ════════════════════════════════════════════════════════════════════════
  // ORTHOPEDIC SURGERY & MUSCULOSKELETAL (5 templates)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "template-ortho-joint-replacement-pathway",
    name: "Joint Replacement (Hip/Knee) Surgical Pathway",
    category: "Orthopedic Surgery & Musculoskeletal",
    specialty: "Orthopedic Surgery",
    description: "Pre-operative clearance, medical optimization, surgical scheduling, post-operative protocol, and rehabilitation pathway.",
    triggerEvent: "JOINT_REPLACEMENT_APPROVED",
    conditions: { procedure: ["hip_replacement", "knee_replacement"] },
    steps: [
      { step: 1, action: "REQUEST_PREOP_CLEARANCE", label: "Pre-op Evaluation", description: "History & physical, EKG, chest X-ray, and labs (CBC, CMP, coagulation studies) for surgical risk assessment." },
      { step: 2, action: "OPTIMIZE_COMORBIDITIES", label: "Medical Optimization", description: "HTN/DM/CAD optimization: ensure BP control, glucose optimization, anticoagulation assessment for bleeding risk." },
      { step: 3, action: "ARRANGE_ANESTHESIA_CONSULTATION", label: "Anesthesia Consult", description: "Anesthesia pre-operative evaluation; discuss anesthesia type (regional vs. general), pain management plan." },
      { step: 4, action: "PLAN_DVTPE_PROPHYLAXIS", label: "Thromboprophylaxis", description: "DVT/PE prophylaxis planning: mechanical (IPC, SCDs) and pharmacologic (enoxaparin or rivaroxaban) per protocol." },
      { step: 5, action: "SCHEDULE_SURGERY_AND_PREOP_TESTING", label: "Surgery Scheduling", description: "Finalize surgery date; arrange labs <30 days pre-op; NPO instructions; medication adjustments (stop ASA 5 days pre-op)." },
      { step: 6, action: "ARRANGE_POSTOP_REHABILITATION", label: "Rehab Planning", description: "Discharge planning: arrange physical therapy (PT/OT) starting post-op day 1; discuss home modifications, assistive devices." },
      { step: 7, action: "CREATE_POSTOP_MONITORING_PROTOCOL", label: "Post-op Protocol", description: "Post-op protocol: pain management (opioid taper), wound checks, DVT surveillance, PT progression (ROM exercises, weight-bearing)." },
    ],
  },
  {
    id: "template-ortho-acl-reconstruction",
    name: "ACL Reconstruction & Sports Return Protocol",
    category: "Orthopedic Surgery & Musculoskeletal",
    specialty: "Orthopedic Surgery",
    description: "Knee injury assessment, graft selection, surgical reconstruction, and evidence-based return-to-sport criteria.",
    triggerEvent: "ACL_TEAR_CONFIRMED",
    conditions: { injuryType: "ACL_tear", athleteStatus: "active" },
    steps: [
      { step: 1, action: "CONFIRM_ACL_DIAGNOSIS", label: "MRI Confirmation", description: "MRI to confirm ACL tear and assess concurrent injuries (meniscal tear, collateral ligament injury, osteochondral lesion)." },
      { step: 2, action: "CLASSIFY_TEAR_PATTERN", label: "Tear Assessment", description: "Classify tear: complete vs. partial; discuss conservative vs. surgical management based on patient goals and activity level." },
      { step: 3, action: "SELECT_GRAFT_TYPE", label: "Graft Selection", description: "Graft options: autograft (patellar tendon, hamstring, quad), allograft, or synthetic; discuss risks/benefits." },
      { step: 4, action: "ARRANGE_PREOP_REHAB", label: "Pre-op PT", description: "Pre-operative physical therapy 2-4 weeks: focus on quad/hamstring strengthening, ROM, knee swelling control." },
      { step: 5, action: "SURGICAL_RECONSTRUCTION", label: "ACL Surgery", description: "Arthroscopic ACL reconstruction with selected graft; concurrent meniscal or cartilage repair if needed." },
      { step: 6, action: "CREATE_POSTOP_REHABILITATION_PROTOCOL", label: "Post-op Protocol", description: "Structured post-op PT protocol: Phase 1 (0-6 wks: ROM, quad sets), Phase 2 (6-12 wks: strengthening), Phase 3 (12-24 wks: sport-specific)." },
      { step: 7, action: "ESTABLISH_RETURN_TO_SPORT_CRITERIA", label: "RTS Criteria", description: "Objective criteria: quad/hamstring strength ratio ≥90%, Y-Balance Test asymmetry <4cm, TimedHop Test ≥90%, isokinetic testing, psychological readiness." },
    ],
  },
  {
    id: "template-ortho-spine-surgery-pathway",
    name: "Spine Surgery (Fusion/Decompression) Pathway",
    category: "Orthopedic Surgery & Musculoskeletal",
    specialty: "Orthopedic Surgery",
    description: "Imaging evaluation, non-operative trial, surgical indication confirmation, fusion planning, and post-operative spinal precautions.",
    triggerEvent: "SPINE_SURGERY_INDICATED",
    conditions: { condition: ["stenosis", "spondylolisthesis", "disc_herniation"] },
    steps: [
      { step: 1, action: "ADVANCED_IMAGING_STUDIES", label: "Imaging Workup", description: "MRI cervical/thoracic/lumbar spine; consider CT for bony anatomy; myelography if imaging equivocal." },
      { step: 2, action: "TRIAL_CONSERVATIVE_MANAGEMENT", label: "Conservative Trial", description: "Attempt conservative management first: PT, NSAIDs, muscle relaxants; ESI (epidural steroid injection) if radiculopathy." },
      { step: 3, action: "CONFIRM_SURGICAL_INDICATION", label: "Surgical Indication", description: "Surgical indication: progressive neurologic deficit, severe/refractory pain, myelopathy with imaging correlation, cauda equina emergency." },
      { step: 4, action: "PLAN_FUSION_LEVELS", label: "Fusion Planning", description: "Determine levels for decompression/fusion; consider biomechanics, adjacent segment disease risk, posterior/anterior approach selection." },
      { step: 5, action: "ARRANGE_INTRAOPERATIVE_MONITORING", label: "Neuromonitoring", description: "Plan for intraoperative neuromonitoring: somatosensory evoked potentials (SSEP), motor evoked potentials (MEP), EMG." },
      { step: 6, action: "PREOP_MEDICAL_OPTIMIZATION", label: "Pre-op Clearance", description: "Medical clearance, anticoagulation assessment, imaging review with anesthesia, discuss fusion complications (non-union, adjacent segment disease)." },
      { step: 7, action: "CREATE_POSTOP_PROTOCOL", label: "Post-op Protocol", description: "Strict spinal precautions: no bending/twisting/lifting; post-op imaging (X-ray); PT progression; brace use per protocol; work restrictions." },
    ],
  },
  {
    id: "template-ortho-fracture-management",
    name: "Acute Fracture Management & Healing Monitoring",
    category: "Orthopedic Surgery & Musculoskeletal",
    specialty: "Orthopedic Surgery",
    description: "Fracture classification, ORIF vs. conservative decision-making, initial reduction/stabilization, and bone healing surveillance.",
    triggerEvent: "FRACTURE_CONFIRMED",
    conditions: { injury: "fracture" },
    steps: [
      { step: 1, action: "CLASSIFY_FRACTURE", label: "Fracture Classification", description: "AO classification or bone-specific system (e.g., femoral neck Garden, pelvic Tile); assess displacement, comminution, angulation." },
      { step: 2, action: "ASSESS_NEUROVASCULAR_STATUS", label: "Vascular Assessment", description: "Document neurovascular exam before and after reduction; obtain vascular studies (CTA, angiography) if vascular compromise." },
      { step: 3, action: "DETERMINE_MANAGEMENT_TYPE", label: "Treatment Decision", description: "ORIF vs. conservative: fracture stability, patient factors (age, bone quality, comorbidities), soft tissue status." },
      { step: 4, action: "INITIAL_REDUCTION_IMMOBILIZATION", label: "Acute Stabilization", description: "Acute stabilization: splinting, casting, or traction; analgesia and antibiotic prophylaxis if open fracture." },
      { step: 5, action: "ARRANGE_SURGICAL_FIXATION", label: "OR Scheduling", description: "ORIF timing: urgent if open fracture, vascular compromise, or compartment syndrome; elective ORIF <3-7 days per fracture type." },
      { step: 6, action: "PLAN_WEIGHT_BEARING_PROGRESSION", label: "Weight-Bearing Plan", description: "Graduated weight-bearing protocol: typically WBAT (weight-bearing as tolerated) for lower extremity at 6-12 weeks per imaging." },
      { step: 7, action: "CREATE_HEALING_SURVEILLANCE_SCHEDULE", label: "Follow-up Imaging", description: "Radiographs at 6 weeks, 12 weeks, and 6 months to assess fracture healing, union progression, implant position; PT progression per healing." },
    ],
  },
  {
    id: "template-ortho-sports-injury-concussion",
    name: "Sports Concussion Management & Return-to-Play",
    category: "Orthopedic Surgery & Musculoskeletal",
    specialty: "Orthopedic Surgery",
    description: "Concussion diagnosis, symptom assessment, neurocognitive testing, graduated return-to-play protocol, and return-to-learn planning.",
    triggerEvent: "CONCUSSION_SUSPECTED",
    conditions: { headInjury: true, lossOfConsciousness: true },
    steps: [
      { step: 1, action: "ASSESS_CONCUSSION_SEVERITY", label: "Symptom Assessment", description: "Document symptoms: headache, dizziness, balance problems, light sensitivity, neck pain; Immediate Post-Concussion Assessment (ImPACT) baseline." },
      { step: 2, action: "NEUROLOGIC_EXAM_SIDELINE", label: "Sideline Exam", description: "Sideline assessment: consciousness, orientation, memory (immediate/delayed recall), balance (Romberg, tandem stance), coordination." },
      { step: 3, action: "OBTAIN_CT_HEAD", label: "Imaging if Indicated", description: "CT head only if concerning features (LOC >seconds, seizure, progressive symptoms); rule out intracranial hemorrhage." },
      { step: 4, action: "BASELINE_NEUROCOGNITIVE_TESTING", label: "Neuro Testing", description: "Computerized neurocognitive testing (ImPACT, CNS Vital Signs) at baseline or within 3 days of injury for comparison." },
      { step: 5, action: "PRESCRIBE_COMPLETE_COGNITIVE_REST", label: "Cognitive Rest", description: "Immediate complete cognitive and physical rest: no school, no sports, no video games, limit screen time until symptom resolution." },
      { step: 6, action: "SCHOOL_COMMUNICATION_FOR_RETURN_TO_LEARN", label: "Return-to-Learn Plan", description: "Return-to-learn timeline: gradual classroom return, reduce homework, frequent breaks, accommodation plan documented with school." },
      { step: 7, action: "GRADUATED_RETURN_TO_PLAY_PROTOCOL", label: "RTP Protocol", description: "6-stage RTP protocol: Stage 1 (light activity <20 min), Stage 2 (sport-specific skills), Stage 3 (non-contact practice), Stage 4 (contact practice), Stage 5 (full practice), Stage 6 (return to competition); 24 hrs symptom-free between stages." },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  // GASTROENTEROLOGY (4 templates)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "template-gi-ibd-crohns-uc-management",
    name: "Inflammatory Bowel Disease (Crohn's/UC) Management",
    category: "Gastroenterology & Hepatology",
    specialty: "Gastroenterology",
    description: "IBD diagnosis confirmation, disease severity assessment, biologic therapy selection, and surveillance colonoscopy planning.",
    triggerEvent: "IBD_DIAGNOSIS_CONFIRMED",
    conditions: { disease: ["Crohns", "ulcerative_colitis"] },
    steps: [
      { step: 1, action: "ASSESS_DISEASE_ACTIVITY", label: "Disease Activity", description: "Assess severity: Mayo Score (UC) or Harvey-Bradshaw Index (Crohn's); CRP, fecal calprotectin, albumin, hemoglobin." },
      { step: 2, action: "CLASSIFY_EXTENT_OF_DISEASE", label: "Disease Extent", description: "Colonoscopy with biopsy to assess inflammation extent (proctitis, left-sided, pancolitis); location in Crohn's." },
      { step: 3, action: "INITIATE_INDUCTION_THERAPY", label: "Induction Treatment", description: "Mild-moderate: 5-ASA (mesalamine) + corticosteroid. Moderate-severe: IV corticosteroid. Severe fulminant: consider hospitalization." },
      { step: 4, action: "SELECT_MAINTENANCE_BIOLOGIC", label: "Biologic Selection", description: "TNF-inhibitor (infliximab, adalimumab), vedolizumab (integrin inhibitor), or ustekinumab (IL-12/23 inhibitor) based on phenotype and response." },
      { step: 5, action: "SCREEN_FOR_COMPLICATIONS", label: "Complications Screening", description: "Screen for strictures (CT enterography for Crohn's), perianal disease, fistulas, toxic megacolon; assess extraintestinal manifestations (arthritis, skin, eye)." },
      { step: 6, action: "MONITOR_BIOLOGIC_THERAPY", label: "Biologic Monitoring", description: "Infusion reactions monitoring, drug/antibody levels, CRP/fecal calprotectin response; assess need for therapy intensification." },
      { step: 7, action: "PLAN_COLORECTAL_CANCER_SURVEILLANCE", label: "CRC Surveillance", description: "Surveillance colonoscopy: every 1-2 years after 8 years of disease onset or if extensive colitis, with targeted biopsies for dysplasia screening." },
    ],
  },
  {
    id: "template-gi-peptic-ulcer-disease",
    name: "Peptic Ulcer Disease (H. pylori & NSAID) Management",
    category: "Gastroenterology & Hepatology",
    specialty: "Gastroenterology",
    description: "H. pylori testing and eradication, PPI optimization, NSAID use assessment, and ulcer healing confirmation.",
    triggerEvent: "PEPTIC_ULCER_DIAGNOSED",
    conditions: { ulcerType: ["gastric", "duodenal"] },
    steps: [
      { step: 1, action: "TEST_FOR_HPYLORI", label: "H. pylori Testing", description: "H. pylori testing: serology, stool antigen, or urea breath test; endoscopic biopsy (urease, culture) if available." },
      { step: 2, action: "ASSESS_NSAID_USE", label: "NSAID Assessment", description: "Assess NSAID use, dose, duration, and indication; review for concurrent aspirin or anticoagulation therapy." },
      { step: 3, action: "DISCONTINUE_NSAID", label: "NSAID Discontinuation", description: "Discontinue NSAID if possible; if necessary, switch to COX-2 selective inhibitor (celecoxib) with PPI co-prescription." },
      { step: 4, action: "INITIATE_PPI_THERAPY", label: "PPI Therapy", description: "PPI monotherapy (omeprazole 20-40 mg daily) to suppress acid and promote ulcer healing." },
      { step: 5, action: "ERADICATE_HPYLORI", label: "H. pylori Eradication", description: "If H. pylori positive: triple or quadruple therapy (PPI + 2-3 antibiotics) for 10-14 days (e.g., PPI + clarithromycin + amoxicillin + metronidazole)." },
      { step: 6, action: "CONFIRM_ULCER_HEALING", label: "Healing Confirmation", description: "Repeat endoscopy at 6-8 weeks if initial ulcer large/complicated or if not responding to therapy." },
      { step: 7, action: "TEST_OF_CURE_HPYLORI", label: "Test of Cure", description: "H. pylori test-of-cure (stool antigen or urea breath test) at least 4 weeks after eradication therapy completion." },
    ],
  },
  {
    id: "template-gi-colorectal-cancer-screening",
    name: "Colorectal Cancer Screening & Polyp Management",
    category: "Gastroenterology & Hepatology",
    specialty: "Gastroenterology",
    description: "Risk stratification, screening modality selection, colonoscopy scheduling, and polyp surveillance intervals.",
    triggerEvent: "CRC_SCREENING_DUE",
    conditions: { ageYears: 50, riskLevel: ["average", "high"] },
    steps: [
      { step: 1, action: "CALCULATE_CRC_RISK", label: "Risk Assessment", description: "Assess risk: average (no personal/family Hx), increased (family Hx CRC <60, IBD, hereditary syndromes)." },
      { step: 2, action: "SELECT_SCREENING_MODALITY", label: "Screening Method", description: "Average risk: colonoscopy every 10 years, FIT annually, or Cologuard every 3 years. High risk: colonoscopy every 3-5 years." },
      { step: 3, action: "PRECOLONOSCOPY_ASSESSMENT", label: "Pre-procedure Workup", description: "CBC, BMP, INR if on anticoagulation; review medications (hold antiplatelet/anticoagulation per protocol)." },
      { step: 4, action: "BOWEL_PREPARATION", label: "Bowel Prep", description: "Bowel preparation: PEG-3350 solution or similar 4 liters with instructions; split-dose prep for better quality." },
      { step: 5, action: "PERFORM_COLONOSCOPY", label: "Procedure Execution", description: "Colonoscopy with polyp identification, biopsy/removal per findings (cold snare for small, hot snare/EMR for larger polyps)." },
      { step: 6, action: "PATHOLOGY_ANALYSIS", label: "Pathology Review", description: "Polyp pathology review: size, histology (hyperplastic, adenoma, sessile serrated), dysplasia grade (low-grade vs. high-grade)." },
      { step: 7, action: "ESTABLISH_SURVEILLANCE_INTERVAL", label: "Surveillance Schedule", description: "Surveillance intervals: normal colonoscopy 10 years, 1-2 small adenomas 5-7 years, advanced adenoma 3 years, multiple/large adenomas 2-3 months follow-up." },
    ],
  },
  {
    id: "template-gi-cirrhosis-decompensation",
    name: "Cirrhosis Decompensation & Complications Management",
    category: "Gastroenterology & Hepatology",
    specialty: "Gastroenterology",
    description: "Ascites management, variceal hemorrhage prophylaxis, hepatic encephalopathy treatment, and transplant evaluation.",
    triggerEvent: "CIRRHOSIS_DECOMPENSATED",
    conditions: { cirrhosisStatus: "decompensated" },
    steps: [
      { step: 1, action: "ASSESS_LIVER_FUNCTION", label: "Liver Assessment", description: "Child-Pugh score, MELD score; INR, albumin, bilirubin, creatinine; ultrasound ± Doppler assessing portal flow." },
      { step: 2, action: "MANAGE_ASCITES", label: "Ascites Management", description: "Diuretics (spironolactone + furosemide); sodium restriction <2g/day; large-volume paracentesis if tense ascites; albumin if SBP." },
      { step: 3, action: "VARICEAL_HEMORRHAGE_PROPHYLAXIS", label: "Variceal Prevention", description: "Endoscopic variceal screening; if varices: beta-blocker (carvedilol, propranolol) prophylaxis or endoscopic band ligation." },
      { step: 4, action: "HEPATIC_ENCEPHALOPATHY_TREATMENT", label: "HE Management", description: "Lactulose titration to 2-3 BM/day; rifaxombin (non-absorbed antibiotic); identify precipitants (infection, bleeding, medication)." },
      { step: 5, action: "SCREEN_FOR_HCC", label: "HCC Surveillance", description: "Ultrasound ± AFP every 6 months for HCC screening if cirrhosis; CT/MRI if focal lesion >10mm." },
      { step: 6, action: "EVALUATE_FOR_TRANSPLANTATION", label: "Transplant Evaluation", description: "Assess transplant candidacy: list if MELD >15; contraindications: active alcohol use, active malignancy, HIV, hepatitis B reactivation risk." },
      { step: 7, action: "PREVENTIVE_THERAPIES", label: "Prevention Measures", description: "Vaccination: HAV/HBV if non-immune, influenza, pneumococcal; avoid NSAIDs; alcohol cessation counseling; nutritional support." },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  // NEPHROLOGY & UROLOGY (4 templates)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "template-nephro-ckd-progression",
    name: "Chronic Kidney Disease (CKD) Staging & Progression Prevention",
    category: "Nephrology & Urology",
    specialty: "Nephrology",
    description: "eGFR monitoring, proteinuria assessment, RAAS inhibitor optimization, mineral metabolism management, and nephrology referral timing.",
    triggerEvent: "CKD_DIAGNOSED",
    conditions: { egfr_range: "30-89" },
    steps: [
      { step: 1, action: "STAGE_CKD", label: "CKD Staging", description: "Stage CKD using eGFR (CKDEPI 2021): Stage 1 (≥90), 2 (60-89), 3a (45-59), 3b (30-44), 4 (15-29), 5 (<15)." },
      { step: 2, action: "ASSESS_ALBUMINURIA", label: "Urine Albumin", description: "Quantify albuminuria (UACR): normal <30, microalbumin 30-300, macroalbuminuria >300 mg/g; trend over time." },
      { step: 3, action: "IDENTIFY_CKD_ETIOLOGY", label: "CKD Workup", description: "Identify etiology: DM (most common), HTN, glomerulonephritis (serology, biopsy if unclear), tubulointerstitial disease, vascular." },
      { step: 4, action: "OPTIMIZE_RAAS_BLOCKADE", label: "ACE-I/ARB Therapy", description: "ACE inhibitor or ARB monotherapy first-line; maximize tolerated dose for renal protection regardless of HTN status." },
      { step: 5, action: "MANAGE_MINERAL_METABOLISM", label: "CKD-MBD Management", description: "Monitor phosphate, calcium, PTH, 25-OH vitamin D; supplement vitamin D if deficient; phosphate binder if PO4 >4.5." },
      { step: 6, action: "BP_GOAL_MANAGEMENT", label: "HTN Management", description: "Target BP <120 if albuminuric, <130/80 if non-albuminuric per KDIGO; add additional agents (CCB, thiazide diuretic) as needed." },
      { step: 7, action: "REFER_TO_NEPHROLOGY", label: "Specialist Referral", description: "Refer to nephrology if eGFR <30, rapid decline (>5 mL/min/year), or if AKI superimposed on CKD." },
    ],
  },
  {
    id: "template-nephro-hemodialysis-initiation",
    name: "End-Stage Renal Disease (ESRD) & Hemodialysis Initiation",
    category: "Nephrology & Urology",
    specialty: "Nephrology",
    description: "ESRD preparation, dialysis modality counseling, vascular access creation, predialysis education, and dialysis commencement.",
    triggerEvent: "ESRD_APPROACHING",
    conditions: { egfr: 10, referralStatus: "planned" },
    steps: [
      { step: 1, action: "PREDIALYSIS_EDUCATION", label: "Patient Education", description: "Comprehensive predialysis education: ESRD treatment options (HD, PD, transplant), vascular access types, dietary restrictions." },
      { step: 2, action: "CHOOSE_DIALYSIS_MODALITY", label: "Modality Selection", description: "Dialysis modality: in-center hemodialysis (3x/week x 4hrs), home hemodialysis (NxHD), peritoneal dialysis (PD), or transplant waitlisting." },
      { step: 3, action: "PLAN_VASCULAR_ACCESS", label: "Access Creation", description: "Vascular access: arteriovenous (AV) fistula (preferred), AV graft, or central venous catheter (CVC); refer to vascular surgeon 6-8 weeks before HD start." },
      { step: 4, action: "MANAGE_PREESRD_COMPLICATIONS", label: "ESRD Preparation", description: "HTN, anemia, bone disease management; start ESA (erythropoietin) if Hgb <10 g/dL; start phosphate binders, calcium, vitamin D." },
      { step: 5, action: "ARRANGE_DIALYSIS_VASCULAR_ACCESS_PLACEMENT", label: "Access Placement", description: "Vascular access creation: AV fistula maturation typically 8-12 weeks before HD initiation; assess for adequacy." },
      { step: 6, action: "DIALYSIS_INITIATION_AND_ASSESSMENT", label: "HD Initiation", description: "Initiate HD when eGFR <10 or symptoms of uremia (nausea, pruritus, confusion); target Kt/V ≥1.2 for adequacy." },
      { step: 7, action: "ONGOING_DIALYSIS_MONITORING", label: "HD Monitoring", description: "Monthly labs: BUN, creatinine, potassium, phosphate, calcium, albumin, Hct; nutrition monitoring; blood pressure management; comorbidity optimization." },
    ],
  },
  {
    id: "template-uro-benign-prostate-hyperplasia",
    name: "Benign Prostatic Hyperplasia (BPH) Diagnosis & Management",
    category: "Nephrology & Urology",
    specialty: "Urology",
    description: "LUTS assessment via IPSS, uroflow studies, post-void residual measurement, medical therapy trials, and TURP consideration.",
    triggerEvent: "LUTS_SYMPTOMS_REPORTED",
    conditions: { symptomDays: 30 },
    steps: [
      { step: 1, action: "ADMINISTER_IPSS_SCORE", label: "IPSS Assessment", description: "International Prostate Symptom Score (IPSS) quantifies lower urinary tract symptoms: storage (frequency, nocturia, urgency) and voiding symptoms." },
      { step: 2, action: "ASSESS_URINARY_FLOW", label: "Uroflow Study", description: "Uroflow study to measure peak flow rate and flow pattern; assess for obstructive pattern (low, prolonged flow)." },
      { step: 3, action: "MEASURE_POSTVOID_RESIDUAL", label: "PVR Measurement", description: "Post-void residual (PVR) by catheterization or ultrasound; elevated PVR (>150 mL) suggests significant obstruction." },
      { step: 4, action: "DIGITAL_RECTAL_EXAM", label: "DRE Exam", description: "Digital rectal exam to assess prostate size, consistency, nodularity; assess PSA level if not previously done." },
      { step: 5, action: "INITIATE_ALPHA_BLOCKER", label: "Alpha Blocker", description: "First-line: alpha-blocker (tamsulosin, terazosin) to relax prostatic smooth muscle; rapid symptom improvement expected within 1-2 weeks." },
      { step: 6, action: "CONSIDER_5ARI", label: "5-Alpha Reductase Inhibitor", description: "If prostate significantly enlarged (PSA >1.5-2) or poor response to alpha-blocker: add 5-ARI (finasteride, dutasteride) for long-term symptom control." },
      { step: 7, action: "PLAN_TRANSURETHRAL_RESECTION", label: "TURP Consideration", description: "If refractory to medical therapy, elevated PVR, or recurrent UTI/hematuria: consider transurethral resection of prostate (TURP)." },
    ],
  },
  {
    id: "template-uro-kidney-stone-management",
    name: "Nephrolithiasis (Kidney Stone) Treatment & Prevention",
    category: "Nephrology & Urology",
    specialty: "Urology",
    description: "Acute colic management, stone composition analysis, imaging surveillance, dietary counseling, and prophylactic therapy.",
    triggerEvent: "KIDNEY_STONE_DIAGNOSED",
    conditions: { stoneDiameter_mm: 5 },
    steps: [
      { step: 1, action: "ACUTE_PAIN_MANAGEMENT", label: "Colic Management", description: "STAT analgesia: IV NSAIDs (ketorolac) or opioids; IV hydration with normal saline; anti-emetics if nauseous." },
      { step: 2, action: "IMAGING_CONFIRMATION", label: "Stone Imaging", description: "CT non-contrast (gold standard) to confirm stone, assess size/location, determine intervention urgency." },
      { step: 3, action: "ASSESS_INFECTION_OBSTRUCTION", label: "Urgent Assessment", description: "Assess for infected obstructed system (emergency requiring decompression); fever + elevated WBC + positive urine culture = emergency." },
      { step: 4, action: "DETERMINE_INTERVENTION_TYPE", label: "Intervention Planning", description: "Small stones (<5mm): observe with hydration, pain management. Large/obstructed: extracorporeal shock wave lithotripsy (ESWL), ureteroscopy, or percutaneous nephrolithotomy." },
      { step: 5, action: "PERFORM_INTERVENTION", label: "Stone Removal", description: "Procedure selection: ESWL (outpatient, non-invasive), ureteroscopy with laser (small-medium stones), PCNL (large stones)." },
      { step: 6, action: "ANALYZE_STONE_COMPOSITION", label: "Stone Analysis", description: "Send stone fragments for composition analysis (calcium oxalate, urate, struvite); informs prevention strategy." },
      { step: 7, action: "IMPLEMENT_PREVENTION_STRATEGY", label: "Prevention Counseling", description: "Dietary counseling: hydration (2-3 L/day urine output), sodium restriction, appropriate protein/calcium intake based on stone type; prophylactic therapy if recurrent." },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  // PULMONOLOGY & RESPIRATORY (4 templates)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "template-pulm-copd-exacerbation",
    name: "COPD Exacerbation Management & Disease Staging",
    category: "Pulmonology & Respiratory",
    specialty: "Pulmonology",
    description: "Exacerbation severity assessment, bronchodilator/corticosteroid therapy, infection management, oxygen titration, and stability monitoring.",
    triggerEvent: "COPD_EXACERBATION_NOTED",
    conditions: { increasedsputum: true, dyspnea_increased: true },
    steps: [
      { step: 1, action: "ASSESS_EXACERBATION_SEVERITY", label: "Severity Assessment", description: "COPD exacerbation assessment: worsening dyspnea, sputum volume/purulence, cough; CURB-65 score if pneumonia suspected." },
      { step: 2, action: "OBTAIN_CHEST_IMAGING", label: "Imaging Workup", description: "Chest X-ray to rule out pneumonia, pneumothorax, or other acute pathology; ABG if SpO2 <90% or altered mental status." },
      { step: 3, action: "INITIATE_BRONCHODILATORS", label: "Bronchodilator Therapy", description: "Albuterol nebulizer treatments (2.5mg) every 20 min x1 hour, then every 1-4 hours; consider ipratropium combination." },
      { step: 4, action: "PRESCRIBE_CORTICOSTEROIDS", label: "Corticosteroid Therapy", description: "IV or oral corticosteroids (prednisone 40-60 mg daily x5-7 days) to reduce inflammation and improve outcomes." },
      { step: 5, action: "TREATMENT_OF_INFECTION", label: "Antibiotic Therapy", description: "If purulent sputum: antibiotics (amoxicillin-clavulanate, fluoroquinolone) for bacterial superinfection; respiratory viral panel if available." },
      { step: 6, action: "OXYGEN_TITRATION", label: "Oxygen Support", description: "Supplemental oxygen titrated to SpO2 88-92% (target lower in CO2 retainers); monitor for CO2 retention if high-risk." },
      { step: 7, action: "CREATE_DISCHARGE_EDUCATION_PLAN", label: "Discharge Planning", description: "Discharge counseling: smoking cessation, flu/pneumococcal vaccination, home oxygen setup, trigger avoidance, action plan for future exacerbations." },
    ],
  },
  {
    id: "template-pulm-idiopathic-pulmonary-fibrosis",
    name: "Idiopathic Pulmonary Fibrosis (IPF) Diagnosis & Antifibrotic Therapy",
    category: "Pulmonology & Respiratory",
    specialty: "Pulmonology",
    description: "Clinical/radiological diagnosis confirmation, disease staging via PFTs, antifibrotic medication initiation, and transplant evaluation.",
    triggerEvent: "IPF_SUSPECTED",
    conditions: { dyspnea_progression: true, restrictive_pattern: true },
    steps: [
      { step: 1, action: "HIGH_RESOLUTION_CT_CHEST", label: "HRCT Imaging", description: "High-resolution CT (HRCT) chest to assess for UIP pattern (usual interstitial pneumonia) showing reticular/ground-glass opacities, traction bronchiectasis." },
      { step: 2, action: "PULMONARY_FUNCTION_TESTING", label: "PFT Studies", description: "Spirometry, lung volumes (FVC, TLC), diffusion capacity (DLCO); assess degree of restriction and gas exchange impairment." },
      { step: 3, action: "RULE_OUT_ALTERNATIVE_DIAGNOSES", label: "Diagnostic Workup", description: "Rule out alternative etiologies: occupational exposure history, connective tissue disease serology (ANA, RF), hypersensitivity pneumonitis history." },
      { step: 4, action: "CONSIDER_LUNG_BIOPSY", label: "Lung Biopsy", description: "Lung biopsy (VATS or bronchoscopic cryobiopsy) if HRCT pattern not diagnostic; clarify diagnosis before antifibrotic therapy initiation." },
      { step: 5, action: "INITIATE_ANTIFIBROTIC_THERAPY", label: "Antifibrotic Drugs", description: "First-line: pirfenidone or nintedanib to slow FVC decline; both show mortality/progression benefit in IPF clinical trials." },
      { step: 6, action: "MONITOR_TOLERABILITY_TOXICITY", label: "Side Effect Monitoring", description: "Monitor tolerability: GI side effects (pirfenidone), diarrhea (nintedanib), hepatic function, drug interactions." },
      { step: 7, action: "ASSESS_TRANSPLANT_CANDIDACY", label: "Transplant Evaluation", description: "Assess lung transplant candidacy: high mortality risk, age <65-70, minimal comorbidities; place on transplant list if appropriate." },
    ],
  },
  {
    id: "template-pulm-pneumonia-complicated",
    name: "Complicated Pneumonia (Empyema/Abscess) Management",
    category: "Pulmonology & Respiratory",
    specialty: "Pulmonology",
    description: "Parapneumonic effusion assessment, empyema diagnosis, thoracentesis/drainage, antibiotic escalation, and surgical consideration.",
    triggerEvent: "COMPLICATED_PNEUMONIA_DOCUMENTED",
    conditions: { pleural_effusion: true, fever_persistent: true },
    steps: [
      { step: 1, action: "OBTAIN_IMAGING_PLEURAL_EFFUSION", label: "Pleural Imaging", description: "Chest X-ray or ultrasound to characterize pleural effusion; assess size (small <1cm, small-moderate 1-2cm, large >2cm on lateral decubitus)." },
      { step: 2, action: "PERFORM_THORACENTESIS", label: "Fluid Analysis", description: "Thoracentesis for pleural fluid analysis: cell count, chemistry (protein, LDH, glucose), pH, gram stain, cultures (aerobic, anaerobic, fungal)." },
      { step: 3, action: "CLASSIFY_EFFUSION_TYPE", label: "Effusion Classification", description: "Light's criteria to classify as exudate vs. transudate; if pH <7.0, low glucose, positive cultures → empyema." },
      { step: 4, action: "ESCALATE_ANTIBIOTIC_THERAPY", label: "Antibiotic Escalation", description: "Empiric coverage: broad-spectrum (3rd gen cephalosporin + fluoroquinolone or clindamycin + gentamicin) with anaerobic coverage." },
      { step: 5, action: "ARRANGE_PLEURAL_DRAINAGE", label: "Drainage Planning", description: "Small-moderate effusions: serial thoracentesis or small-bore chest tube. Large or loculated: larger tube or VATS for drainage/break up loculations." },
      { step: 6, action: "FIBRINOLYTIC_THERAPY_CONSIDERATION", label: "Fibrinolytic Therapy", description: "Consider intrapleural fibrinolytic therapy (tPA/DNase) if septated effusion or loculation; improves drainage effectiveness." },
      { step: 7, action: "VATS_EVALUATION", label: "Surgical Consideration", description: "If multiloculated, no improvement with drainage/fibrinolytics, or thick pleural peel: refer for VATS pleurodesis or decortication." },
    ],
  },
];
