// ============================================================================
// INTENSIVE WORKFLOW TEMPLATES - SPECIALTY & DOMAIN-SPECIFIC WORKFLOWS
// ============================================================================
// This file contains 60+ production-ready workflow templates organized by
// medical specialty and clinical domain. All templates follow secure-by-default
// patterns with verified session identity binding for audit trails.
// ============================================================================

export const INTENSIVE_WORKFLOW_TEMPLATES = [
  // ════════════════════════════════════════════════════════════════════════
  // ONCOLOGY & CANCER CARE (8 templates)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "template-oncology-initial-consult",
    name: "Oncology Initial Consultation & Staging Workflow",
    category: "Oncology & Cancer Care",
    specialty: "Oncology",
    description: "Comprehensive intake workflow for new cancer patients including biopsy verification, tumor staging via imaging, TNM classification, molecular profiling, genetic counseling referral, and multidisciplinary tumor board scheduling.",
    triggerEvent: "ONCOLOGY_PATIENT_REGISTERED",
    conditions: { specialty: "oncology", patientType: "new" },
    steps: [
      { step: 1, action: "REQUEST_PATHOLOGY_REVIEW", label: "Order Pathology Review", description: "Request pathologist review of biopsy specimens and confirm malignancy diagnosis." },
      { step: 2, action: "SCHEDULE_IMAGING_PROTOCOL", label: "Schedule TNM Staging", description: "Order comprehensive imaging (CT/MRI/PET) protocol based on cancer type for TNM staging." },
      { step: 3, action: "TRIGGER_MOLECULAR_TESTING", label: "Request Genomic Profiling", description: "Order tumor genomic sequencing (FoundationOne, Guardant, or similar) for targeted therapy eligibility." },
      { step: 4, action: "CREATE_TASK", label: "Genetics Consultation", description: "Create task to schedule genetic counselor visit if hereditary cancer syndrome suspected." },
      { step: 5, action: "SEND_PATIENT_EDUCATION", label: "Treatment Education", description: "Send patient education materials on cancer types, staging, and treatment modalities." },
      { step: 6, action: "SCHEDULE_MULTIDISCIPLINARY_MEETING", label: "Schedule Tumor Board", description: "Queue patient case for multidisciplinary tumor board review before treatment planning." },
    ],
  },
  {
    id: "template-oncology-chemotherapy-cycle",
    name: "Chemotherapy Administration & Cycle Management",
    category: "Oncology & Cancer Care",
    specialty: "Oncology",
    description: "Pre-treatment workup, chemotherapy administration, side-effect monitoring, and cycle-to-cycle follow-up including pre-chemo labs, cardiotoxicity screening, nutritional support, and toxicity documentation.",
    triggerEvent: "CHEMO_CYCLE_INITIATED",
    conditions: { treatmentType: "chemotherapy" },
    steps: [
      { step: 1, action: "REQUEST_LAB_PANEL", label: "Order Pre-Chemo Labs", description: "CBC, CMP, renal function, liver function, and tumor markers baseline." },
      { step: 2, action: "ORDER_CARDIAC_ASSESSMENT", label: "Cardiotoxicity Screening", description: "EKG and echocardiogram for cardiotoxic agents (doxorubicin, trastuzumab)." },
      { step: 3, action: "CREATE_ANTIEMETIC_PROTOCOL", label: "Antiemetic Plan", description: "Pre-script 5-HT3 antagonist, NK1 inhibitor, and corticosteroid protocol." },
      { step: 4, action: "SEND_SMS_NOTIFICATION", label: "Cycle Reminder", description: "Send SMS reminder 24 hours before chemotherapy infusion appointment." },
      { step: 5, action: "LOG_TREATMENT_DELIVERY", label: "Document Administration", description: "Record chemotherapy agents, doses, routes, and any infusion reactions." },
      { step: 6, action: "CREATE_FOLLOW_UP_TASK", label: "Schedule Day-3 Check-in", description: "Task RN to call patient on day 3 for nausea/vomiting assessment." },
      { step: 7, action: "REQUEST_NUTRITION_CONSULT", label: "Nutritionist Referral", description: "Refer to oncology nutritionist for appetite support and weight management." },
    ],
  },
  {
    id: "template-oncology-radiation-planning",
    name: "Radiation Therapy Planning & Daily Treatment",
    category: "Oncology & Cancer Care",
    specialty: "Oncology",
    description: "CT simulation, treatment planning approval, weekly physics checks, skin assessment, and radiation dermatitis management with automated escalation for severe reactions.",
    triggerEvent: "RADIATION_THERAPY_APPROVED",
    conditions: { treatmentType: "radiation" },
    steps: [
      { step: 1, action: "SCHEDULE_CT_SIMULATION", label: "Schedule CT Sim", description: "Book CT simulation appointment with immobilization device fabrication." },
      { step: 2, action: "NOTIFY_RADIATION_ONCOLOGY", label: "Alert Physics Team", description: "Notify radiation oncology physics team to begin treatment planning after CT sim." },
      { step: 3, action: "CREATE_DAILY_TASK", label: "Skin Assessment Task", description: "Create recurring daily task for RN to assess skin for erythema/desquamation." },
      { step: 4, action: "SEND_RADIATION_EDUCATION", label: "Patient Education", description: "Send educational materials on radiation safety, side effects, and skin care." },
      { step: 5, action: "SCHEDULE_WEEKLY_PHYSICS_CHECK", label: "Physics QA Weekly", description: "Schedule weekly physics check-in to review dose distribution and treatment accuracy." },
      { step: 6, action: "SETUP_DERMATITIS_ESCALATION", label: "Monitor Skin Toxicity", description: "Establish escalation protocol: Grade 2 → dermatology consult, Grade 3+ → dose hold evaluation." },
    ],
  },
  {
    id: "template-oncology-immunotherapy-monitoring",
    name: "Immunotherapy (Checkpoint Inhibitor) Monitoring",
    category: "Oncology & Cancer Care",
    specialty: "Oncology",
    description: "Baseline immune profiling, pre-treatment screening, per-cycle immune checkpoint labs, and automated immune-related adverse event (irAE) detection with specialist escalation.",
    triggerEvent: "IMMUNOTHERAPY_CYCLE_START",
    conditions: { treatmentType: "immunotherapy" },
    steps: [
      { step: 1, action: "REQUEST_BASELINE_LABS", label: "Baseline Immune Panel", description: "TSH, LFTs, renal panel, lipase, and immune profiling baseline." },
      { step: 2, action: "SCREEN_AUTOIMMUNE_HISTORY", label: "AI Risk Assessment", description: "Review patient history for autoimmune disease, rheumatologic conditions, prior anti-CTLA-4." },
      { step: 3, action: "SEND_IRAS_EDUCATION", label: "irAE Education Materials", description: "Patient education on immune-related adverse events: rash, colitis, pneumonitis, endocrinopathy." },
      { step: 4, action: "REQUEST_LABS_PER_CYCLE", label: "Cycle Labs", description: "TSH, LFTs, lipase, CBC before each infusion to monitor immune activation." },
      { step: 5, action: "CREATE_SYMPTOM_CHECK_IN", label: "Weekly Symptom Check-in", description: "Weekly automated symptom assessment: rash severity, diarrhea, dyspnea, fatigue." },
      { step: 6, action: "ESCALATE_GRADE2_IRAS", label: "Grade 2+ irAE Escalation", description: "Auto-escalate Grade 2+ irAE (e.g., colitis) to GI, Pulm, Endo specialists." },
      { step: 7, action: "CREATE_STEROID_PROTOCOL", label: "Steroid Dosing Plan", description: "If irAE diagnosed, create prednisolone taper protocol and taper tracker." },
    ],
  },
  {
    id: "template-oncology-clinical-trial-enrollment",
    name: "Clinical Trial Enrollment & Study Compliance",
    category: "Oncology & Cancer Care",
    specialty: "Oncology",
    description: "Eligibility screening, informed consent management, IRB documentation, baseline assessments, randomization, and study visit scheduling with protocol violation alerts.",
    triggerEvent: "TRIAL_ELIGIBILITY_REVIEW",
    conditions: { patientEligible: true },
    steps: [
      { step: 1, action: "VERIFY_INCLUSION_CRITERIA", label: "Inclusion Criteria Check", description: "Automated validation of tumor type, stage, prior treatments, organ function against trial protocol." },
      { step: 2, action: "SEND_ICF_DOCUMENT", label: "Send Informed Consent", description: "Electronic delivery of ICF (Informed Consent Form) and patient information sheet." },
      { step: 3, action: "CREATE_BASELINE_VISIT_TASK", label: "Baseline Assessment", description: "Schedule baseline visit with bloodwork, imaging, and ECOG performance status documentation." },
      { step: 4, action: "NOTIFY_RANDOMIZATION_TEAM", label: "Randomization Request", description: "Submit patient to IWRS (Interactive Web Response System) for treatment arm randomization." },
      { step: 5, action: "GENERATE_CALENDAR_OF_EVENTS", label: "Study Calendar", description: "Generate study calendar with visit windows, labs due dates, and imaging schedules." },
      { step: 6, action: "CREATE_PROTOCOL_ALERT", label: "Protocol Deviation Alerts", description: "Set alerts for protocol deviations: missed visit windows, untimely labs, dose delays." },
      { step: 7, action: "SCHEDULE_QUERY_RESPONSE", label: "CRF Query Management", description: "Notify research coordinator of data review queries from CRO (Contract Research Organization)." },
    ],
  },
  {
    id: "template-oncology-palliative-transition",
    name: "Transition to Palliative Care & Symptom Management",
    category: "Oncology & Cancer Care",
    specialty: "Oncology",
    description: "Treatment failure recognition, palliative care referral, advance directive discussion, symptom control optimization, and coordination with hospice when appropriate.",
    triggerEvent: "DISEASE_PROGRESSION_NOTED",
    conditions: { progressionStatus: "progressive_disease" },
    steps: [
      { step: 1, action: "SEND_PROVIDER_ALERT", label: "Provider Notification", description: "Alert oncologist and primary team of imaging findings or tumor marker progression." },
      { step: 2, action: "CREATE_PALLIATIVE_CONSULT_TASK", label: "Palliative Consult", description: "Create task to schedule palliative care physician consult for symptom management planning." },
      { step: 3, action: "SEND_ADVANCE_DIRECTIVE_MATERIALS", label: "Advance Directive", description: "Send electronic advance directive, POLST form, and goals-of-care discussion prompts." },
      { step: 4, action: "SCHEDULE_FAMILY_MEETING", label: "Goals of Care Meeting", description: "Schedule multidisciplinary family meeting with oncology, palliative, social work, chaplain." },
      { step: 5, action: "CREATE_SYMPTOM_PROTOCOL", label: "Symptom Management", description: "Establish pain, nausea, dyspnea, anxiety protocols with PRN medication templates." },
      { step: 6, action: "REFER_PSYCHOSOCIAL_SUPPORT", label: "Mental Health Support", description: "Referral to oncology psychologist, support groups, and caregiver resources." },
      { step: 7, action: "NOTIFY_HOSPICE_COORDINATION", label: "Hospice Inquiry", description: "If appropriate, initiate conversation with hospice providers for potential care transition." },
    ],
  },
  {
    id: "template-oncology-survivorship-planning",
    name: "Cancer Survivorship Plan & Long-Term Follow-up",
    category: "Oncology & Cancer Care",
    specialty: "Oncology",
    description: "Treatment summary generation, late toxicity monitoring, recurrence surveillance, preventive health optimization, and psychosocial follow-up for cancer survivors.",
    triggerEvent: "TREATMENT_COMPLETED",
    conditions: { treatmentStatus: "completed" },
    steps: [
      { step: 1, action: "GENERATE_TREATMENT_SUMMARY", label: "Treatment Summary", description: "Create comprehensive survivorship care plan: diagnoses, treatments, surgeries, chemotherapy agents, doses." },
      { step: 2, action: "SEND_SURVIVORSHIP_PLAN", label: "Send to PCP", description: "Share survivorship plan with primary care physician for coordination of follow-up care." },
      { step: 3, action: "CREATE_SURVEILLANCE_PROTOCOL", label: "Surveillance Schedule", description: "Generate follow-up schedule for imaging, labs, and clinical visits based on cancer type and stage." },
      { step: 4, action: "SCREEN_LATE_TOXICITIES", label: "Late Toxicity Screening", description: "Baseline assessment for common late effects: cardiac dysfunction, secondary malignancies, infertility." },
      { step: 5, action: "SEND_PREVENTIVE_HEALTH_PLAN", label: "Preventive Care", description: "Screening for age-appropriate preventive care: colonoscopy, mammography, cardiovascular risk reduction." },
      { step: 6, action: "CREATE_FERTILITY_COUNSELING_TASK", label: "Fertility Preservation", description: "For reproductive-age patients: discuss fertility preservation options, reproductive goals, counseling." },
      { step: 7, action: "REFER_SURVIVORSHIP_SUPPORT", label: "Support Resources", description: "Refer to cancer survivor support groups, financial counseling, vocational rehabilitation resources." },
    ],
  },
  {
    id: "template-oncology-end-of-life-documentation",
    name: "End-of-Life Care & Code Status Documentation",
    category: "Oncology & Cancer Care",
    specialty: "Oncology",
    description: "Code status discussion, POLST completion, symptom crisis response, family communication templates, and post-mortem coordination.",
    triggerEvent: "END_OF_LIFE_CARE_INITIATED",
    conditions: { prognosis: "terminal" },
    steps: [
      { step: 1, action: "DOCUMENT_CODE_STATUS", label: "Code Status Order", description: "Document full code/DNR/DNI/CMO decision in order set with patient/surrogate signature." },
      { step: 2, action: "COMPLETE_POLST_FORM", label: "POLST Completion", description: "Complete POLST form with treatment intensity preferences, MOLST signing, and transmit to EMS." },
      { step: 3, action: "CREATE_CRISIS_PROTOCOL", label: "Symptom Crisis Plan", description: "Create protocol for acute symptom crises: respiratory distress, severe pain, hemorrhage, seizures." },
      { step: 4, action: "SEND_FAMILY_COMMUNICATION", label: "Family Updates", description: "Schedule regular family calls/meetings to discuss status changes and answer questions." },
      { step: 5, action: "COORDINATE_SPIRITUAL_CARE", label: "Spiritual Support", description: "Referral to chaplain, social work, and community spiritual resources per patient/family preference." },
      { step: 6, action: "PREPARE_DEATH_PLANNING", label: "Death Planning", description: "Assist with funeral planning, DNR placement, organ donation discussion, and final wishes documentation." },
      { step: 7, action: "SCHEDULE_BEREAVEMENT_FOLLOW_UP", label: "Bereavement Support", description: "Post-death family follow-up, bereavement support group referrals, and clinical team debriefing." },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  // CARDIOLOGY (7 templates)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "template-cardiology-acute-coronary",
    name: "Acute Coronary Syndrome (ACS) Alert & PCI Coordination",
    category: "Cardiology & Cardiovascular",
    specialty: "Cardiology",
    description: "STEMI/NSTEMI detection, cath lab activation, door-to-balloon time tracking, dual antiplatelet therapy initiation, and post-intervention monitoring.",
    triggerEvent: "ACS_ALERT_TRIGGERED",
    conditions: { severity: "acute" },
    steps: [
      { step: 1, action: "ALERT_INTERVENTIONAL_CARDIOLOGY", label: "Cath Lab Alert", description: "Activate cath lab team with STEMI protocol or NSTEMI observation unit notification." },
      { step: 2, action: "INITIATE_DUAL_ANTIPLATELET", label: "Load DAPT", description: "Administer loading doses of aspirin (325mg) and P2Y12 inhibitor (clopidogrel/ticagrelor/prasugrel)." },
      { step: 3, action: "SEND_STAT_LAB_ORDER", label: "STAT Labs", description: "Order STAT troponin, CBC, BMP, coagulation studies, and lipid panel." },
      { step: 4, action: "TRACK_DOOR_TO_BALLOON", label: "Time Tracking", description: "Record door-to-ECG, door-to-cath lab, and door-to-balloon times for quality metrics." },
      { step: 5, action: "CREATE_ICU_BED_REQUEST", label: "ICU Admission", description: "Request CCU/ICU bed with continuous cardiac monitoring setup." },
      { step: 6, action: "SEND_FAMILY_NOTIFICATION", label: "Family Alert", description: "Notify family of acute cardiac event and expected procedure timeline." },
      { step: 7, action: "SCHEDULE_POST_PCI_ECHO", label: "Post-PCI Assessment", description: "Schedule echocardiogram within 24-48 hours to assess cardiac function and complications." },
    ],
  },
  {
    id: "template-cardiology-heart-failure-admission",
    name: "Acute Decompensated Heart Failure Admission Protocol",
    category: "Cardiology & Cardiovascular",
    specialty: "Cardiology",
    description: "Volume status assessment, diuretic titration, guideline-directed medical therapy optimization, and discharge planning with close outpatient follow-up.",
    triggerEvent: "HF_ADMISSION_DOCUMENTED",
    conditions: { diagnosis: "acute_heart_failure" },
    steps: [
      { step: 1, action: "REQUEST_COMPREHENSIVE_LAB_PANEL", label: "HF Labs", description: "BNP/NT-proBNP, troponin, CBC, BMP, LFTs, TSH, and iron studies." },
      { step: 2, action: "ORDER_IMAGING_PROTOCOL", label: "Cardiac Imaging", description: "Chest X-ray and echocardiography to assess cardiac function and determine HF type (HFrEF vs HFpEF)." },
      { step: 3, action: "INITIATE_DIURETIC_PROTOCOL", label: "Diuretic Titration", description: "Start/uptitrate loop diuretic with daily weights and input/output monitoring." },
      { step: 4, action: "OPTIMIZE_GDMT", label: "GDMT Optimization", description: "Initiate/optimize ACE-I/ARB, beta-blocker, MRA per HF guidelines; titrate as tolerated." },
      { step: 5, action: "CREATE_DAILY_ASSESSMENT_TASK", label: "Daily Rounds Task", description: "Create daily assessment task: orthopnea/PND/edema/weight changes/renal function trending." },
      { step: 6, action: "REFER_CARDIOLOGY_CONSULTATION", label: "Cardiology Consult", description: "Referral to inpatient cardiology for echocardiogram interpretation and device consideration (if EF <35%)." },
      { step: 7, action: "PLAN_DISCHARGE_EDUCATION", label: "Discharge Education", description: "Setup discharge education: sodium/fluid restriction, daily weights, medication adherence, outpatient follow-up in 1 week." },
    ],
  },
  {
    id: "template-cardiology-arrhythmia-management",
    name: "Cardiac Arrhythmia Risk Stratification & Device Planning",
    category: "Cardiology & Cardiovascular",
    specialty: "Cardiology",
    description: "ECG analysis, EP study feasibility assessment, antiarrhythmic medication selection, and device implantation planning (pacemaker, ICD, CRT) with procedural scheduling.",
    triggerEvent: "ARRHYTHMIA_DOCUMENTED",
    conditions: { arrhythmiaType: ["atrial_fibrillation", "ventricular_tachycardia", "bradycardia"] },
    steps: [
      { step: 1, action: "ORDER_EXTENDED_RHYTHM_MONITORING", label: "Holter/Event Monitor", description: "24-48 hour Holter monitor or 30-day event monitor to characterize arrhythmia frequency and triggers." },
      { step: 2, action: "ASSESS_ANTICOAGULATION_NEED", label: "Stroke Risk (CHA2DS2-VASc)", description: "Calculate CHA2DS2-VASc score; initiate anticoagulation if ≥2 (males) or ≥3 (females)." },
      { step: 3, action: "REVIEW_ANTIARRHYTHMIC_HISTORY", label: "Drug Trial History", description: "Review prior antiarrhythmic medication trials, efficacy, and side effects to guide next therapy." },
      { step: 4, action: "SCHEDULE_EP_STUDY", label: "EP Study Planning", description: "If recurrent SVT/VT despite medication: schedule EP study for ablation vs device evaluation." },
      { step: 5, action: "ASSESS_DEVICE_INDICATION", label: "Device Eligibility", description: "Evaluate for pacemaker (bradycardia), ICD (primary/secondary prevention of sudden cardiac death), or CRT (HFrEF + conduction delay)." },
      { step: 6, action: "COORDINATE_DEVICE_IMPLANTATION", label: "Device Procedure", description: "Schedule device implantation with pre-op clearance, device selection, and post-op monitoring plan." },
      { step: 7, action: "CREATE_DEVICE_FOLLOW_UP_SCHEDULE", label: "Device Clinic Schedule", description: "Create recurring device clinic visits: 2 weeks post-implant, then quarterly interrogations." },
    ],
  },
  {
    id: "template-cardiology-valve-disease-assessment",
    name: "Valvular Heart Disease Assessment & Intervention Planning",
    category: "Cardiology & Cardiovascular",
    specialty: "Cardiology",
    description: "Echocardiographic surveillance, hemodynamic assessment, surgical vs. interventional planning, endocarditis prophylaxis, and prosthetic valve anticoagulation management.",
    triggerEvent: "VALVE_DISEASE_DIAGNOSED",
    conditions: { disease: ["mitral_stenosis", "aortic_stenosis", "mitral_regurgitation", "aortic_regurgitation"] },
    steps: [
      { step: 1, action: "ORDER_TRANSESOPHAGEAL_ECHO", label: "TEE Imaging", description: "Transesophageal echocardiography for detailed valve morphology, anatomy, and severity assessment." },
      { step: 2, action: "CALCULATE_HEMODYNAMIC_BURDEN", label: "Hemodynamics", description: "Assess valve area, gradients, jet velocity, and left/right chamber size and function." },
      { step: 3, action: "ASSESS_SURGICAL_RISK", label: "Operative Risk", description: "STS risk calculator, EuroSCORE II, and frailty assessment to guide surgical vs. transcatheter approach." },
      { step: 4, action: "CREATE_ENDOCARDITIS_PROPHYLAXIS", label: "Infection Prophylaxis", description: "Issue antibiotic prophylaxis guidelines for dental/procedures if moderate to high-risk lesion." },
      { step: 5, action: "PLAN_INTERVENTION_TIMING", label: "Intervention Planning", description: "Determine timing of surgical or transcatheter valve intervention based on symptoms and hemodynamic thresholds." },
      { step: 6, action: "COORDINATE_MULTIDISCIPLINARY_MEETING", label: "Heart Team Meeting", description: "Schedule multidisciplinary heart team meeting (cardiology, cardiac surgery, anesthesia, ICU) for case review." },
      { step: 7, action: "SCHEDULE_PROCEDURE_WORKUP", label: "Pre-Intervention Workup", description: "Schedule CT angiography, cardiac MRI, coronary angiography, and other pre-operative imaging." },
    ],
  },
  {
    id: "template-cardiology-hypertension-optimization",
    name: "Resistant Hypertension Management & Refractory HTN Workup",
    category: "Cardiology & Cardiovascular",
    specialty: "Cardiology",
    description: "Out-of-office BP monitoring, secondary HTN screening, medication adherence assessment, and specialist referral for resistant hypertension.",
    triggerEvent: "RESISTANT_HYPERTENSION_DOCUMENTED",
    conditions: { bpControl: "uncontrolled", medicationCount: 3 },
    steps: [
      { step: 1, action: "ORDER_HOME_BP_MONITORING", label: "Home BP Monitoring", description: "Supply home BP monitor and request 7-day BP log (AM and PM readings) for out-of-office confirmation." },
      { step: 2, action: "ASSESS_MEDICATION_ADHERENCE", label: "Adherence Assessment", description: "Patient education and adherence counseling; consider pharmacy refill records and pill counts." },
      { step: 3, action: "SCREEN_SECONDARY_CAUSES", label: "Secondary Screening", description: "Lab workup: TSH, plasma renin/aldosterone ratio, sleep apnea screening, urine drug screen." },
      { step: 4, action: "ORDER_RENAL_ARTERY_IMAGING", label: "Renal Artery Imaging", description: "If suspicious for renovascular HTN: CT angiography or renal doppler ultrasound." },
      { step: 5, action: "OPTIMIZE_CURRENT_REGIMEN", label: "Medication Optimization", description: "Uptitrate current agents to maximum tolerated doses; add complementary class (e.g., add diuretic if not on one)." },
      { step: 6, action: "CONSIDER_SPECIALIST_INTERVENTION", label: "Specialist Referral", description: "Refer to hypertension specialist for refractory HTN; consider renal denervation trial eligibility if resistant." },
      { step: 7, action: "CREATE_BP_TRACKING_PROTOCOL", label: "Monitoring Protocol", description: "Create monthly clinic visits with BP check and medication adjustment until BP goal achieved." },
    ],
  },
  {
    id: "template-cardiology-lipid-optimization",
    name: "Lipid Management & Cardiovascular Risk Reduction",
    category: "Cardiology & Cardiovascular",
    specialty: "Cardiology",
    description: "Risk stratification, statin initiation/intensification, PCSK9 inhibitor eligibility assessment, and lifestyle modification counseling.",
    triggerEvent: "CARDIOVASCULAR_RISK_ASSESSMENT",
    conditions: { riskLevel: ["high", "very_high"] },
    steps: [
      { step: 1, action: "CALCULATE_ASCVD_RISK", label: "Risk Score", description: "Calculate 10-year ASCVD risk using ACC/AHA Risk Calculator based on age, sex, race, BP, lipids, diabetes, smoking." },
      { step: 2, action: "ORDER_COMPREHENSIVE_LIPID_PANEL", label: "Lipid Panel", description: "Total cholesterol, LDL, HDL, triglycerides, Lp(a), and apoB if high-risk or familial hypercholesterolemia." },
      { step: 3, action: "INITIATE_HIGH_INTENSITY_STATIN", label: "Statin Therapy", description: "High-intensity statin (atorvastatin 80mg or rosuvastatin 40mg) if ASCVD or high-risk per guidelines." },
      { step: 4, action: "SCREEN_MUSCLE_SIDE_EFFECTS", label: "Statin Tolerance", description: "Baseline muscle symptoms assessment; if intolerant, try alternative statin or ezetimibe addition." },
      { step: 5, action: "ASSESS_PCSK9_ELIGIBILITY", label: "PCSK9 Inhibitor", description: "If LDL >70 on high-intensity statin or statin intolerant: consider PCSK9i (evolocumab, alirocumab, inclisiran)." },
      { step: 6, action: "REFER_LIFESTYLE_INTERVENTION", label: "Lifestyle Counseling", description: "Referral to nutritionist for heart-healthy diet, exercise program, and smoking cessation if applicable." },
      { step: 7, action: "CREATE_LIPID_RECHECK_SCHEDULE", label: "Recheck Labs", description: "Schedule lipid panel recheck 4-12 weeks after initiation/change to assess LDL response and medication adherence." },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  // NEUROLOGY & NEUROSURGERY (6 templates)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "template-neurology-acute-stroke",
    name: "Acute Ischemic Stroke (AIS) thrombolytic/thrombectomy Protocol",
    category: "Neurology & Neurosurgery",
    specialty: "Neurology",
    description: "Rapid stroke team activation, NIH Stroke Scale assessment, IV tPA decision, mechanical thrombectomy evaluation, and post-intervention monitoring.",
    triggerEvent: "STROKE_CODE_ACTIVATED",
    conditions: { strokeType: "acute_ischemic" },
    steps: [
      { step: 1, action: "ACTIVATE_STROKE_TEAM", label: "Stroke Team Alert", description: "Stat page neurology, neuroradiology, ED attending; activate code stroke protocol." },
      { step: 2, action: "STAT_NON_CONTRAST_CT", label: "CT Head", description: "Stat non-contrast CT to rule out hemorrhage; confirm ischemic stroke diagnosis." },
      { step: 3, action: "ASSESS_NIHSS", label: "NIH Stroke Scale", description: "Bedside NIH Stroke Scale assessment by neurologist to quantify deficit severity." },
      { step: 4, action: "DETERMINE_THROMBOLYTIC_ELIGIBILITY", label: "tPA Decision", description: "Check inclusion/exclusion criteria; if eligible and within 3-4.5 hours: administer IV alteplase (tPA) 0.9 mg/kg." },
      { step: 5, action: "EVALUATE_THROMBECTOMY", label: "Thrombectomy Assessment", description: "Large vessel occlusion assessment; if LVO with proximal occlusion: activate interventional lab for mechanical thrombectomy." },
      { step: 6, action: "TRACK_STROKE_TIMES", label: "Time Metrics", description: "Record door-to-CT, CT-to-tPA, door-to-thrombectomy times for quality assurance." },
      { step: 7, action: "SCHEDULE_STROKE_UNIT_ADMISSION", label: "Stroke Unit Bed", description: "Admit to stroke unit with continuous neuro monitoring, q1h assessments, and post-intervention imaging." },
    ],
  },
  {
    id: "template-neurology-seizure-management",
    name: "Seizure Disorder Diagnosis & Antiepileptic Therapy",
    category: "Neurology & Neurosurgery",
    specialty: "Neurology",
    description: "Seizure semiology assessment, EEG monitoring, MRI with epilepsy protocol, medication selection, and status epilepticus emergency response.",
    triggerEvent: "SEIZURE_DOCUMENTED",
    conditions: { seizureType: ["generalized", "focal"] },
    steps: [
      { step: 1, action: "SCHEDULE_EEG_MONITORING", label: "EEG Study", description: "Routine EEG or prolonged monitoring (24-48 hours) to document seizure activity and localize focus." },
      { step: 2, action: "ORDER_MRI_EPILEPSY_PROTOCOL", label: "Brain MRI", description: "High-resolution MRI with epilepsy protocol to identify structural lesions (tumor, AVM, scarring, malformation)." },
      { step: 3, action: "CLASSIFY_SEIZURE_TYPE", label: "Seizure Classification", description: "Determine seizure type per ILAE classification (generalized tonic-clonic, absence, myoclonic, focal, focal-to-bilateral)." },
      { step: 4, action: "SELECT_ANTIEPILEPTIC_DRUG", label: "Medication Selection", description: "Choose first-line AED based on seizure type, comorbidities, drug interactions (levetiracetam, lamotrigine, valproate, oxcarbazepine)." },
      { step: 4, action: "CREATE_AED_TITRATION_SCHEDULE", label: "AED Titration", description: "Slow titration schedule for AED with follow-up labs (LFTs, drug levels) and seizure frequency tracking." },
      { step: 6, action: "ESTABLISH_STATUS_EPILEPTICUS_PROTOCOL", label: "Emergency Protocol", description: "Patient/family education on seizure first aid; prescribe rescue benzodiazepine (midazolam nasal spray or rectal diazepam)." },
      { step: 7, action: "ASSESS_EPILEPSY_SURGERY_CANDIDACY", label: "Surgery Evaluation", description: "If pharmacoresistant (failed 2 appropriate AEDs): refer for comprehensive pre-surgical epilepsy evaluation." },
    ],
  },
  {
    id: "template-neurology-neurodegenerative-monitoring",
    name: "Neurodegenerative Disease Monitoring (ALS, PD, AD Protocol)",
    category: "Neurology & Neurosurgery",
    specialty: "Neurology",
    description: "Disease progression tracking, multidisciplinary symptom management, pulmonary/nutritional support, and palliative care coordination.",
    triggerEvent: "NEURODEGENERATIVE_DIAGNOSIS",
    conditions: { disease: ["ALS", "Parkinson", "Alzheimer"] },
    steps: [
      { step: 1, action: "CREATE_BASELINE_FUNCTIONAL_ASSESSMENT", label: "Baseline FRS/MoCA", description: "Baseline functional rating scale (ALS-FRS-R, UPDRS for PD, MMSE/MoCA for dementia)." },
      { step: 2, action: "ESTABLISH_MONITORING_SCHEDULE", label: "Visit Schedule", description: "Create quarterly neurology visits with disease-specific rating scales to track progression rate." },
      { step: 3, action: "ASSESS_RESPIRATORY_FUNCTION", label: "Pulmonary Assessment", description: "Baseline and recurring FVC, sleep study, and sleep apnea screening; refer to pulmonology if declining." },
      { step: 4, action: "OPTIMIZE_SYMPTOMATIC_THERAPY", label: "Symptom Management", description: "Medication optimization: dopamine agonists for PD, riluzole for ALS, cholinesterase inhibitor for AD." },
      { step: 5, action: "REFER_MULTIDISCIPLINARY_SUPPORT", label: "Multidisciplinary Team", description: "Referral to speech-language pathology (swallow/communication), PT/OT (mobility/ADL), and social work." },
      { step: 6, action: "COORDINATE_NUTRITIONAL_SUPPORT", label: "Nutrition Planning", description: "Nutrition assessment; discuss feeding tube options if swallowing decline or weight loss noted." },
      { step: 7, action: "INITIATE_ADVANCE_CARE_PLANNING", label: "Advance Planning", description: "Early goals-of-care discussions, advance directives, POLST completion, and hospice introduction if appropriate." },
    ],
  },
  {
    id: "template-neurology-headache-management",
    name: "Chronic Migraine & Headache Disorder Management",
    category: "Neurology & Neurosurgery",
    specialty: "Neurology",
    description: "Migraine classification, preventive medication selection, neuromodulation device evaluation, and botulinum toxin planning.",
    triggerEvent: "CHRONIC_MIGRAINE_DIAGNOSED",
    conditions: { headacheDays: 15, migraineHeadaches: 8 },
    steps: [
      { step: 1, action: "CREATE_HEADACHE_DIARY", label: "Headache Diary", description: "30-day headache diary tracking: frequency, severity (0-10), duration, triggers, aura, associated symptoms, medications used." },
      { step: 2, action: "CLASSIFY_MIGRAINE_TYPE", label: "Migraine Classification", description: "Determine episodic vs. chronic migraine; classify with aura/without aura; assess medication overuse headache risk." },
      { step: 3, action: "SCREEN_SECONDARY_CAUSES", label: "Secondary Screening", description: "Brain MRI to rule out structural pathology; if red flags: CT, LP, or vascular imaging as indicated." },
      { step: 4, action: "INITIATE_PREVENTIVE_THERAPY", label: "Preventive Medication", description: "First-line preventives: propranolol, topiramate, amitriptyline, or candesartan titrated per tolerability." },
      { step: 5, action: "ASSESS_CGRP_INHIBITOR_ELIGIBILITY", label: "CGRP Antagonist", description: "If ≥4 migraines/month despite preventive trial: consider CGRP monoclonal antibodies (erenumab, fremanezumab, galcanezumab)." },
      { step: 6, action: "EVALUATE_BOTULINUM_TOXIN", label: "Botox Protocol", description: "For chronic migraine (≥15 headache days/month): consider botulinum toxin injections (Botox) protocol." },
      { step: 7, action: "CONSIDER_NEUROMODULATION_DEVICE", label: "Device Evaluation", description: "If refractory: assess for neurostimulation (occipital nerve stimulation, vagal nerve stimulation) device candidacy." },
    ],
  },
  {
    id: "template-neurology-ms-disease-modifying",
    name: "Multiple Sclerosis (MS) Treatment & Disease Modification",
    category: "Neurology & Neurosurgery",
    specialty: "Neurology",
    description: "Relapse protocol, MRI surveillance, disease-modifying therapy selection, and long-term disability monitoring.",
    triggerEvent: "MS_RELAPSE_REPORTED",
    conditions: { msType: ["relapsing_remitting", "secondary_progressive"] },
    steps: [
      { step: 1, action: "ASSESS_RELAPSE_SEVERITY", label: "Relapse Assessment", description: "Document new symptoms, EDSS score (Expanded Disability Status Scale), and functional impact assessment." },
      { step: 2, action: "INITIATE_CORTICOSTEROID_PROTOCOL", label: "Corticosteroid Therapy", description: "High-dose IV methylprednisolone 1g daily x3 days for moderate-to-severe relapse; follow with oral taper." },
      { step: 3, action: "ORDER_BRAIN_SPINAL_CORD_MRI", label: "MRI Monitoring", description: "Brain and spinal cord MRI with and without contrast to assess lesion burden and new/enhancing lesions." },
      { step: 4, action: "CONSIDER_PLASMA_EXCHANGE", label: "PLEX if Severe", description: "If fulminant relapse not responding to steroids within 72 hours: consider plasma exchange (PLEX) or IVIG." },
      { step: 5, action: "OPTIMIZE_DISEASE_MODIFYING_THERAPY", label: "DMT Optimization", description: "Assess current DMT efficacy; escalate to more potent agents (natalizumab, fingolimod, ocrelizumab) if breakthrough relapses." },
      { step: 6, action: "CREATE_MRI_SURVEILLANCE_PROTOCOL", label: "MRI Schedule", description: "Annual baseline MRI then tailored interval based on disease activity; more frequent if breakthrough relapses." },
      { step: 7, action: "COORDINATE_REHABILITATION_SERVICES", label: "Rehab Referral", description: "Refer to physical therapy, occupational therapy, and speech-language pathology based on neurologic deficits." },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  // INFECTIOUS DISEASE (6 templates)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "template-id-sepsis-protocol",
    name: "Sepsis Recognition & Early Antibiotic Protocol",
    category: "Infectious Disease",
    specialty: "Infectious Disease",
    description: "qSOFA scoring, lactate monitoring, rapid blood cultures, empiric broad-spectrum antibiotics, source control, and fluid resuscitation.",
    triggerEvent: "SEPSIS_CRITERIA_MET",
    conditions: { qSOFA_score: 2, lactate_elevated: true },
    steps: [
      { step: 1, action: "DOCUMENT_SEPSIS_DIAGNOSIS", label: "Sepsis Documentation", description: "Document qSOFA score (altered mental status, SBP <100, respiratory rate >22) and SIRS criteria." },
      { step: 2, action: "OBTAIN_BLOOD_CULTURES", label: "Blood Cultures x2", description: "STAT blood cultures from 2 separate sites before any antibiotic administration." },
      { step: 3, action: "INITIATE_BROAD_SPECTRUM_ANTIBIOTICS", label: "Empiric Antibiotics", description: "STAT empiric antibiotics within 1 hour (e.g., 3rd gen cephalosporin + fluoroquinolone or linezolid per sepsis site)." },
      { step: 4, action: "ORDER_LACTATE_MEASUREMENT", label: "Lactate Check", description: "Initial and repeat lactate at 3 hours; elevated or rising lactate indicates tissue hypoperfusion." },
      { step: 5, action: "INITIATE_FLUID_BOLUS", label: "Fluid Resuscitation", description: "30 mL/kg crystalloid IV fluid bolus over first hour targeting MAP >65 or UOP >0.5 mL/kg/hr." },
      { step: 6, action: "IDENTIFY_INFECTION_SOURCE", label: "Source Control", description: "Urgent imaging (CT, ultrasound) and cultures to identify infection source; surgery consult if surgical source." },
      { step: 7, action: "ARRANGE_ICU_ADMISSION", label: "ICU Monitoring", description: "Admit to ICU for continuous monitoring, vasopressor support if needed, and daily antibiotic de-escalation." },
    ],
  },
  {
    id: "template-id-pneumonia-management",
    name: "Community-Acquired Pneumonia (CAP) Diagnosis & Treatment",
    category: "Infectious Disease",
    specialty: "Infectious Disease",
    description: "Severity assessment via CURB-65, microbiologic workup, empiric antibiotic selection, and outpatient vs. admission decision.",
    triggerEvent: "PNEUMONIA_DIAGNOSED",
    conditions: { coughDuration: 3, fever: true },
    steps: [
      { step: 1, action: "CALCULATE_CURB65_SCORE", label: "CURB-65 Score", description: "Calculate CURB-65 (Confusion, Urea >7, Respiratory rate >30, BP systolic <90, age ≥65) to guide admission vs. outpatient." },
      { step: 2, action: "ORDER_CHEST_XRAY", label: "Chest Imaging", description: "Chest X-ray to confirm infiltrate; consider CT if atypical presentation or immunocompromised." },
      { step: 3, action: "OBTAIN_RESPIRATORY_CULTURES", label: "Microbiologic Workup", description: "Sputum culture (if productive) and blood cultures if hospitalized; respiratory viral panel if available." },
      { step: 4, action: "PRESCRIBE_EMPIRIC_ANTIBIOTICS", label: "Empiric Therapy", description: "Outpatient: amoxicillin-clavulanate or fluoroquinolone. Hospitalized: 3rd gen cephalosporin ± macrolide or fluoroquinolone." },
      { step: 5, action: "ASSESS_OXYGEN_REQUIREMENT", label: "Oxygen Support", description: "If SpO2 <90%: initiate supplemental oxygen targeting SpO2 >94%; arrange admission if requiring oxygen." },
      { step: 6, action: "CREATE_FOLLOW_UP_IMAGING", label: "Repeat Imaging", description: "Schedule repeat chest X-ray at 4-6 weeks in smokers and patients >50 to rule out malignancy." },
      { step: 7, action: "SEND_PNEUMOCOCCAL_VACCINE_REMINDER", label: "Vaccination", description: "Prescribe pneumococcal vaccine (PPSV23 and/or PCV20) per current guidelines if not previously vaccinated." },
    ],
  },
  {
    id: "template-id-hiv-management",
    name: "HIV Diagnosis & Antiretroviral Therapy Initiation",
    category: "Infectious Disease",
    specialty: "Infectious Disease",
    description: "Baseline CD4/viral load testing, opportunistic infection screening, ART regimen selection, and adherence counseling.",
    triggerEvent: "HIV_DIAGNOSIS_CONFIRMED",
    conditions: { hiv_positive: true },
    steps: [
      { step: 1, action: "CONFIRM_HIV_STATUS", label: "HIV Confirmation", description: "Confirm HIV diagnosis with Western blot or HIV RNA (viral load) if initial screening positive." },
      { step: 2, action: "BASELINE_IMMUNOLOGIC_TESTING", label: "CD4 & Viral Load", description: "Baseline CD4 count and HIV RNA viral load to determine disease stage and ART urgency." },
      { step: 3, action: "SCREEN_FOR_OIS", label: "OI Screening", description: "Screen for opportunistic infections: TB (IGRA/TST), CMV (fundoscopy if CD4 <50), PCP (TMP-SMX ppx if CD4 <200)." },
      { step: 4, action: "ORDER_RESISTANCE_TESTING", label: "Genotypic Testing", description: "Baseline genotypic drug resistance testing to guide ART regimen selection." },
      { step: 5, action: "SELECT_ART_REGIMEN", label: "ART Selection", description: "Select integrase-based ART regimen (e.g., bictegravir/TAF/FTC, dolutegravir + 2 NRTIs) per patient factors and resistance." },
      { step: 6, action: "INITIATE_ADHERENCE_COUNSELING", label: "Adherence Counseling", description: "Intensive adherence counseling, pill organizers, smartphone app support, and mental health/substance use screening." },
      { step: 7, action: "CREATE_CD4_MONITORING_SCHEDULE", label: "Follow-up Labs", description: "CD4 and viral load monitoring: at 4 weeks, 8 weeks, 12 weeks, then every 3 months after virologic suppression." },
    ],
  },
  {
    id: "template-id-hepatitis-c-treatment",
    name: "Hepatitis C Virus (HCV) Eradication Therapy",
    category: "Infectious Disease",
    specialty: "Infectious Disease",
    description: "Genotype testing, cirrhosis assessment, DAA regimen selection, SVR monitoring, and liver disease surveillance.",
    triggerEvent: "HCV_ANTIBODY_POSITIVE",
    conditions: { hcv_positive: true },
    steps: [
      { step: 1, action: "CONFIRM_HCV_VIREMIA", label: "HCV RNA Testing", description: "Confirm active HCV infection with HCV RNA (viral load); quantify viral load if positive." },
      { step: 2, action: "ORDER_GENOTYPE_TESTING", label: "HCV Genotype", description: "HCV genotype and subtype testing to determine DAA regimen selection and treatment duration." },
      { step: 3, action: "ASSESS_LIVER_FIBROSIS", label: "Fibrosis Assessment", description: "FibroTest/FibroScan elastography or liver biopsy to stage fibrosis (F0-F4) and assess cirrhosis risk." },
      { step: 4, action: "SCREEN_FOR_HCC", label: "HCC Screening", description: "If cirrhosis (F4): baseline abdominal ultrasound with AFP to screen for hepatocellular carcinoma." },
      { step: 5, action: "PRESCRIBE_DAA_REGIMEN", label: "DAA Therapy", description: "Prescribe direct-acting antiviral regimen (sofosbuvir/velpatasvir ± velpatasvir/sofosbuvir/velpatasvir ± ribavirin) for 8-12 weeks." },
      { step: 6, action: "COUNSEL_ON_DRUG_INTERACTIONS", label: "Drug Interactions", description: "Screen for drug interactions with DAAs; counsel on adherence and expected side effect profile." },
      { step: 7, action: "CREATE_SVR_FOLLOW_UP", label: "SVR Monitoring", description: "HCV RNA testing at end-of-treatment and 12 weeks after (SVR12) to confirm viral eradication." },
    ],
  },
  {
    id: "template-id-tb-treatment",
    name: "Tuberculosis (TB) Diagnosis & Anti-TB Therapy",
    category: "Infectious Disease",
    specialty: "Infectious Disease",
    description: "TB screening, diagnosis confirmation, drug-susceptibility testing, multi-drug therapy, and directly observed therapy (DOT) coordination.",
    triggerEvent: "TB_DIAGNOSIS_CONFIRMED",
    conditions: { tb_positive: true },
    steps: [
      { step: 1, action: "CONFIRM_TB_DIAGNOSIS", label: "TB Confirmation", description: "Chest X-ray showing infiltrates + sputum smear microscopy or TB culture positive, or GeneXpert MTB/RIF positive." },
      { step: 2, action: "CLASSIFY_TB_TYPE", label: "TB Classification", description: "Classify as active pulmonary TB, extrapulmonary TB (meningitis, lymphadenitis, pericarditis), or latent TB infection." },
      { step: 3, action: "ORDER_DRUG_SUSCEPTIBILITY_TESTING", label: "DST Testing", description: "Sputum culture with DST to rifampin and isoniazid; consider MDR-TB or XDR-TB if resistant." },
      { step: 4, action: "INITIATE_4_DRUG_REGIMEN", label: "Anti-TB Therapy", description: "Intensive phase (2 months): isoniazid, rifampin, pyrazinamide, ethambutol daily. Continuation phase (4 months): isoniazid + rifampin." },
      { step: 5, action: "SCREEN_CONTACTS", label: "Contact Tracing", description: "Identify and screen close contacts (household, workplace); treat latent TB with 3-6 months isoniazid or 3-4 months rifampin." },
      { step: 6, action: "ARRANGE_DIRECTLY_OBSERVED_THERAPY", label: "DOT Coordination", description: "Directly observed therapy (DOT) at clinic 2-3x/week to ensure adherence and monitor for toxicity." },
      { step: 7, action: "MONITOR_TREATMENT_RESPONSE", label: "Treatment Monitoring", description: "Repeat sputum smear/culture at 2, 5, and end-of-treatment to confirm bacteriologic response." },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  // PSYCHIATRY & MENTAL HEALTH (5 templates)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "template-psych-depression-protocol",
    name: "Depression Diagnosis & Antidepressant Initiation",
    category: "Psychiatry & Mental Health",
    specialty: "Psychiatry",
    description: "PHQ-9 screening, severity assessment, antidepressant selection, and psychotherapy coordination.",
    triggerEvent: "DEPRESSION_SCREENING_POSITIVE",
    conditions: { phq9_score: 10, duration_weeks: 2 },
    steps: [
      { step: 1, action: "ADMINISTER_PHQ9", label: "PHQ-9 Assessment", description: "Administer PHQ-9 to quantify depression severity (5-9 mild, 10-14 moderate, 15-19 moderately severe, 20+ severe)." },
      { step: 2, action: "ASSESS_SUICIDALITY", label: "Suicide Risk Assessment", description: "Suicide risk assessment: ideation, intent, access to means; safety planning if moderate-to-high risk." },
      { step: 3, action: "SCREEN_BIPOLAR_DISORDER", label: "Bipolar Screening", description: "Assess for bipolar disorder history (manic/hypomanic episodes) to avoid antidepressant-induced mania." },
      { step: 4, action: "COMPLETE_MEDICAL_WORKUP", label: "Medical Screening", description: "Screen for medical causes: thyroid dysfunction, B12 deficiency, chronic disease, medication side effects." },
      { step: 5, action: "SELECT_ANTIDEPRESSANT", label: "Medication Selection", description: "First-line SSRI or SNRI (sertraline, escitalopram, citalopram, venlafaxine) based on side effect profile and comorbidities." },
      { step: 6, action: "REFER_PSYCHOTHERAPY", label: "Therapy Referral", description: "Concurrent referral to therapist for evidence-based psychotherapy (CBT, interpersonal therapy) to enhance outcomes." },
      { step: 7, action: "CREATE_FOLLOW_UP_PROTOCOL", label: "Follow-up Schedule", description: "Follow-up at 2-4 weeks to assess response and side effects; target 6-8 weeks for full antidepressant effect." },
    ],
  },
  {
    id: "template-psych-anxiety-disorder",
    name: "Anxiety Disorder Management & Treatment Planning",
    category: "Psychiatry & Mental Health",
    specialty: "Psychiatry",
    description: "GAD-7 assessment, disorder classification, pharmacotherapy options, and CBT coordination.",
    triggerEvent: "ANXIETY_SYMPTOMS_REPORTED",
    conditions: { gad7_score: 10, duration_weeks: 4 },
    steps: [
      { step: 1, action: "ADMINISTER_GAD7", label: "GAD-7 Assessment", description: "Administer GAD-7 (5-9 mild, 10-14 moderate, 15+ severe) to quantify anxiety symptom burden." },
      { step: 2, action: "CLASSIFY_ANXIETY_DISORDER", label: "Disorder Classification", description: "Differentiate generalized anxiety disorder (GAD), panic disorder, social anxiety, agoraphobia, or specific phobia." },
      { step: 3, action: "ASSESS_DEPRESSION_COMORBIDITY", label: "Comorbidity Check", description: "Screen for concurrent depression (PHQ-9) and substance use as these commonly co-occur with anxiety disorders." },
      { step: 4, action: "RULE_OUT_MEDICAL_CAUSES", label: "Medical Screening", description: "Screen for medical causes: hyperthyroidism, caffeine overuse, cardiac arrhythmias, chronic pulmonary disease." },
      { step: 5, action: "INITIATE_SSRI_THERAPY", label: "Pharmacotherapy", description: "First-line SSRI (sertraline, paroxetine, escitalopram) or SNRI (venlafaxine) for anxiety disorders." },
      { step: 6, action: "REFER_CBT", label: "Cognitive Behavioral Therapy", description: "Concurrent referral to therapist trained in exposure therapy and cognitive restructuring (gold standard for anxiety)." },
      { step: 7, action: "CREATE_RELAXATION_RESOURCES", label: "Self-Help Resources", description: "Provide relaxation techniques (deep breathing, progressive muscle relaxation), meditation apps, and support group resources." },
    ],
  },
  {
    id: "template-psych-bipolar-disorder-stabilization",
    name: "Bipolar Disorder Management & Mood Stabilization",
    category: "Psychiatry & Mental Health",
    specialty: "Psychiatry",
    description: "Mood episode classification, mood stabilizer selection, lithium monitoring protocols, and psychoeducation.",
    triggerEvent: "BIPOLAR_DISORDER_DIAGNOSED",
    conditions: { moodEpisodeHistory: "documented" },
    steps: [
      { step: 1, action: "ASSESS_MOOD_EPISODE_TYPE", label: "Episode Classification", description: "Classify current/recent mood state: mania/hypomania (elevated mood), depression, or mixed features per DSM-5." },
      { step: 2, action: "OBTAIN_MOOD_STABILIZER_BASELINE", label: "Baseline Labs", description: "Baseline labs: CBC, BMP, TSH, LFTs, lithium level if starting lithium; pregnancy test if female." },
      { step: 3, action: "SELECT_MOOD_STABILIZER", label: "Mood Stabilizer", description: "First-line options: lithium, valproate, lamotrigine, or atypical antipsychotic (olanzapine, quetiapine) based on phase." },
      { step: 4, action: "IF_LITHIUM_CHOSEN", label: "Lithium Protocol", description: "Initiate lithium at 600 mg BID, titrate to serum level 0.6-1.2 mEq/L; monitor renal/thyroid function every 6-12 months." },
      { step: 5, action: "PSYCHOEDUCATION_SESSION", label: "Patient Education", description: "Comprehensive psychoeducation: bipolar disorder pathophysiology, medication adherence importance, trigger identification, relapse prevention." },
      { step: 6, action: "CREATE_CRISIS_PLAN", label: "Crisis Planning", description: "Develop written crisis plan with early warning signs, emergency contacts, emergency therapist/psychiatrist, and hospitalization threshold." },
      { step: 7, action: "SCHEDULE_FREQUENT_MONITORING", label: "Follow-up Schedule", description: "Frequent monitoring: weekly x4 weeks, then biweekly until stable, then monthly; mood tracking with PHQ-9/YMRS." },
    ],
  },
  {
    id: "template-psych-substance-abuse-treatment",
    name: "Substance Use Disorder Assessment & Addiction Treatment",
    category: "Psychiatry & Mental Health",
    specialty: "Psychiatry",
    description: "AUDIT/DAST screening, withdrawal risk assessment, medication-assisted treatment (MAT) planning, and recovery support coordination.",
    triggerEvent: "SUBSTANCE_USE_SCREENING_POSITIVE",
    conditions: { substance_involvement: true },
    steps: [
      { step: 1, action: "ADMINISTER_SUBSTANCE_SCREENING", label: "AUDIT/DAST-10", description: "AUDIT for alcohol (score ≥8 concerning) or DAST-10 for drugs (score ≥3 concerning) severity assessment." },
      { step: 2, action: "ASSESS_WITHDRAWAL_RISK", label: "Withdrawal Assessment", description: "Assess withdrawal risk per substance: alcohol (autonomic instability, seizures), opioids (dysphoria, not life-threatening), benzodiazepines." },
      { step: 3, action: "INITIATE_DETOXIFICATION", label: "Detox Protocol", description: "Alcohol: benzodiazepine taper (CIWA protocol); Opioids: buprenorphine induction; Benzodiazepines: slow taper over weeks." },
      { step: 4, action: "SCREEN_MENTAL_HEALTH_COMORBIDITY", label: "Psychiatric Comorbidity", description: "Screen for depression, anxiety, trauma, bipolar disorder commonly co-occurring with substance use disorders." },
      { step: 5, action: "INITIATE_MEDICATION_ASSISTED_TREATMENT", label: "MAT Planning", description: "For opioid use disorder: buprenorphine/naloxone maintenance or methadone program enrollment per preference." },
      { step: 6, action: "REFER_BEHAVIORAL_THERAPY", label: "Addiction Counseling", description: "Referral to addiction counselor trained in motivational interviewing and cognitive-behavioral relapse prevention therapy." },
      { step: 7, action: "COORDINATE_RECOVERY_SUPPORT", label: "Support Groups", description: "Connect to peer support: AA/SMART Recovery for alcohol, NA/SMART Recovery for drugs, with sponsor/accountability partner." },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  // ENDOCRINOLOGY (5 templates)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "template-endo-diabetes-type2-management",
    name: "Type 2 Diabetes Diagnosis & Glycemic Management",
    category: "Endocrinology & Metabolic",
    specialty: "Endocrinology",
    description: "HbA1c monitoring, diabetes education, oral agent selection, GLP-1 RA/SGLT2i consideration for cardiovascular/renal protection.",
    triggerEvent: "DIABETES_TYPE2_DIAGNOSED",
    conditions: { hba1c: 6.5, fasting_glucose: 126 },
    steps: [
      { step: 1, action: "BASELINE_DIABETES_LABS", label: "Baseline Labs", description: "HbA1c, fasting glucose, comprehensive metabolic panel, lipid panel, urine microalbumin, TSH." },
      { step: 2, action: "COMPREHENSIVE_DIABETES_EDUCATION", label: "Diabetes Education", description: "Referral to certified diabetes educator (CDE) for carbohydrate counting, foot care, sick day management, blood glucose self-monitoring." },
      { step: 3, action: "INITIATE_METFORMIN_THERAPY", label: "Metformin Initiation", description: "First-line: metformin 500 mg BID with titration to 1000 mg BID as tolerated, with lifestyle modifications (diet, exercise)." },
      { step: 4, action: "ASSESS_CARDIO_RENAL_RISK", label: "Complication Screening", description: "Screen for microvascular (retinopathy, nephropathy, neuropathy) and macrovascular complications; assess cardiovascular/CKD risk." },
      { step: 5, action: "CONSIDER_GLP1_SGLT2i", label: "Add-on Therapy", description: "If HbA1c not at goal or high CV/renal risk: add GLP-1 RA (semaglutide) or SGLT2i (empagliflozin) for cardio-renal benefits." },
      { step: 6, action: "ARRANGE_ANNUAL_SCREENING", label: "Annual Surveillance", description: "Annual dilated eye exam (ophthalmology), urine microalbumin, comprehensive foot exam, and EKG if risk factors." },
      { step: 7, action: "CREATE_HBA1C_MONITORING_SCHEDULE", label: "Follow-up Labs", description: "HbA1c monitoring: at 3 months after medication change, then every 3-6 months; target HbA1c <7% per guidelines." },
    ],
  },
  {
    id: "template-endo-thyroid-disorder",
    name: "Thyroid Disorder Management (Hypothyroid & Hyperthyroid)",
    category: "Endocrinology & Metabolic",
    specialty: "Endocrinology",
    description: "TSH/free T4 monitoring, levothyroxine/antithyroid agent dosing, and disease-specific screening and follow-up.",
    triggerEvent: "THYROID_DYSFUNCTION_DIAGNOSED",
    conditions: { tsh_abnormal: true },
    steps: [
      { step: 1, action: "CLASSIFY_THYROID_DISORDER", label: "Thyroid Classification", description: "Hypothyroidism (elevated TSH, low free T4) vs. Hyperthyroidism (suppressed TSH, elevated free T4/T3) vs. Central hypothyroidism." },
      { step: 2, action: "DETERMINE_ETIOLOGY", label: "Etiology Workup", description: "Hypothyroidism: TPO antibodies (Hashimoto's); Hyperthyroidism: TSH receptor antibodies (Graves') or thyroid ultrasound." },
      { step: 3, action: "INITIATE_LEVOTHYROXINE_OR_ANTITHYROID", label: "Medication Initiation", description: "Hypothyroidism: levothyroxine 25-50 mcg daily with titration. Hyperthyroidism: PTU or methimazole antithyroid agents." },
      { step: 4, action: "COUNSEL_ON_ABSORPTION", label: "Patient Education", description: "Take levothyroxine on empty stomach 30-60 min before food; separate from calcium, iron, coffee by 4+ hours." },
      { step: 5, action: "SCREEN_GRAVES_COMPLICATIONS", label: "Graves' Screening", label: "If Graves' disease: screen for thyroid-associated ophthalmopathy (exophthalmos, diplopia) and refer to endocrinology." },
      { step: 6, action: "PLAN_TSH_RECHECK", label: "TSH Follow-up", description: "Recheck TSH at 6 weeks after initiation/change, then every 3 months until stable, then annually." },
      { step: 7, action: "IF_GRAVES_CONSIDER_DEFINITIVE", label: "Treatment Options", description: "For persistent Graves': consider definitive therapy (radioactive iodine ablation or thyroidectomy) in consultation with endocrinology." },
    ],
  },
  {
    id: "template-endo-adrenal-insufficiency",
    name: "Adrenal Insufficiency Diagnosis & Glucocorticoid Replacement",
    category: "Endocrinology & Metabolic",
    specialty: "Endocrinology",
    description: "Adrenal crisis recognition, ACTH/cortisol testing, hydrocortisone/prednisone replacement, and patient education on stress dosing.",
    triggerEvent: "ADRENAL_INSUFFICIENCY_SUSPECTED",
    conditions: { cortisol_low: true },
    steps: [
      { step: 1, action: "RECOGNIZE_ADRENAL_CRISIS", label: "Crisis Recognition", description: "Signs: hypotension, tachycardia, hyponatremia, hyperkalemia, abdominal pain, altered mental status; STAT treat with IV hydrocortisone 100mg." },
      { step: 2, action: "PERFORM_ACTH_CORTISOL_TEST", label: "Diagnostic Testing", description: "Early morning (7-9am) serum cortisol and ACTH; if cortisol <3 mcg/dL: ACTH stimulation test (cosyntropin) for confirmation." },
      { step: 3, action: "CLASSIFY_INSUFFICIENCY_TYPE", label: "Classification", description: "Primary (elevated ACTH): autoimmune Addison's, TB, adrenalitis. Secondary (low ACTH): pituitary/hypothalamic disease." },
      { step: 4, action: "INITIATE_GLUCOCORTICOID_REPLACEMENT", label: "Replacement Therapy", description: "Hydrocortisone 20-30 mg daily in divided doses or prednisone 5-7.5 mg daily to match normal cortisol production." },
      { step: 4, action: "ADD_MINERALOCORTICOID_IF_PRIMARY", label: "Fludrocortisone", description: "If primary insufficiency: fludrocortisone acetate 0.05-0.1 mg daily to retain sodium and prevent hypotension." },
      { step: 6, action: "STRESS_DOSING_EDUCATION", label: "Patient Education", description: "Educate on stress-dose steroids: double or triple hydrocortisone dose during illness, surgery, trauma, or emotional stress." },
      { step: 7, action: "CREATE_MEDICAL_ALERT_SYSTEM", label: "Emergency Preparedness", description: "Provide medical alert bracelet/card, injectable hydrocortisone emergency kit, and documentation for healthcare providers." },
    ],
  },
  {
    id: "template-endo-osteoporosis-prevention",
    name: "Osteoporosis Screening & Fracture Prevention",
    category: "Endocrinology & Metabolic",
    specialty: "Endocrinology",
    description: "DEXA screening, 10-year fracture risk assessment, calcium/vitamin D supplementation, and bisphosphonate therapy planning.",
    triggerEvent: "OSTEOPOROSIS_SCREENING_INDICATED",
    conditions: { age: 65, risk_factors: true },
    steps: [
      { step: 1, action: "ORDER_BONE_DENSITY_DEXA", label: "DEXA Scan", description: "Dual-energy X-ray absorptiometry (DEXA) of hip, spine, and forearm to measure bone mineral density (T-score)." },
      { step: 2, action: "CALCULATE_FRACTURE_RISK", label: "FRAX Score", description: "10-year probability of hip fracture and major osteoporotic fracture using FRAX tool incorporating DEXA T-score and clinical factors." },
      { step: 3, action: "ASSESS_SECONDARY_CAUSES", label: "Secondary Causes", description: "Screen for secondary osteoporosis: hyperthyroidism, hyperparathyroidism, multiple myeloma, chronic kidney disease, malabsorption." },
      { step: 4, action: "OPTIMIZE_CALCIUM_VITAMIN_D", label: "Calcium/Vitamin D", description: "Calcium 1000-1200 mg/day + vitamin D 800-1000 IU/day (higher if deficiency); baseline 25-OH vitamin D level." },
      { step: 5, action: "ASSESS_BISPHOSPHONATE_INDICATION", label: "Pharmacotherapy", description: "If T-score <-2.5 (osteoporosis) or FRAX 10-year hip fracture ≥3%: bisphosphonate (alendronate weekly or zoledronic acid yearly)." },
      { step: 6, action: "COUNSEL_ON_FALL_PREVENTION", label: "Fall Prevention", description: "Home safety evaluation, vision/hearing screening, medication review (sedating drugs), physical therapy for balance/strength." },
      { step: 7, action: "SCHEDULE_REPEAT_DEXA", label: "Monitoring Protocol", description: "Repeat DEXA every 2 years on therapy to assess bone density response; adjust therapy if continued decline." },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════
  // PEDIATRICS (5 templates)
  // ════════════════════════════════════════════════════════════════════════
  {
    id: "template-peds-newborn-screening",
    name: "Newborn Screening & Early Intervention Protocol",
    category: "Pediatrics & Child Health",
    specialty: "Pediatrics",
    description: "Expanded newborn screening panel interpretation, congenital disorder diagnosis, specialist referral, and family counseling.",
    triggerEvent: "NEWBORN_SCREENING_POSITIVE",
    conditions: { abnormalResult: true },
    steps: [
      { step: 1, action: "CONFIRM_ABNORMAL_RESULT", label: "Repeat Testing", description: "Repeat newborn screening test to confirm abnormal result; order second-tier testing (MS/MS, enzyme assay) if available." },
      { step: 2, action: "IDENTIFY_DISORDER_CATEGORY", label: "Disorder Category", description: "Categorize: metabolic (PKU, MSUD, maple syrup urine), hemoglobinopathy (sickle cell), endocrine (congenital hypothyroidism), or immunodeficiency." },
      { step: 3, action: "REFER_SPECIALIST_IMMEDIATELY", label: "Specialist Referral", description: "URGENT referral to specialist: metabolic disease physician, pediatric endocrinologist, hematologist, or immunologist for confirmation." },
      { step: 4, action: "INITIATE_DIETARY_MANAGEMENT", label: "Dietary Intervention", description: "If metabolic disorder: specialized formula (low-phenylalanine, BCAA-free) or dietary restrictions to prevent intellectual disability." },
      { step: 5, action: "START_MEDICAL_THERAPY", label: "Medical Treatment", description: "Medical management per disorder: L-DOPA for tyrosinemia, vitamin B12 for methylmalonic aciduria, hydroxyurea for sickle cell." },
      { step: 6, action: "PROVIDE_FAMILY_COUNSELING", label: "Family Education", description: "Genetic counseling, family screening if autosomal recessive, support group referrals, and long-term prognosis discussion." },
      { step: 7, action: "CREATE_LONG_TERM_MONITORING", label: "Follow-up Plan", description: "Close follow-up: weekly x4 weeks, then monthly x6 months, then every 3 months for developmental milestones and treatment optimization." },
    ],
  },
  {
    id: "template-peds-asthma-control",
    name: "Pediatric Asthma Diagnosis & Control Protocol",
    category: "Pediatrics & Child Health",
    specialty: "Pediatrics",
    description: "Asthma diagnosis confirmation, controller vs. reliever medication selection, trigger identification, and school/sports planning.",
    triggerEvent: "ASTHMA_DIAGNOSED",
    conditions: { recurrentWheezing: true },
    steps: [
      { step: 1, action: "CONFIRM_ASTHMA_DIAGNOSIS", label: "Spirometry/PFT", description: "Spirometry showing reversible airway obstruction (FEV1 increase >12% post-bronchodilator) to confirm asthma diagnosis." },
      { step: 2, action: "ASSESS_ASTHMA_SEVERITY", label: "Severity Classification", description: "Classify: intermittent, mild persistent, moderate persistent, or severe persistent per frequency of symptoms and nighttime awakenings." },
      { step: 3, action: "IDENTIFY_ASTHMA_TRIGGERS", label: "Trigger Assessment", description: "Common triggers: allergens (dust mites, pollen, pets), respiratory infections, exercise, cold air, irritants (smoke, pollution)." },
      { step: 4, action: "PRESCRIBE_CONTROLLER_THERAPY", label: "Controller Inhaler", description: "Mild-moderate: inhaled corticosteroid (ICS) monotherapy. Severe: ICS + long-acting beta-2 agonist (LABA) combination." },
      { step: 5, action: "PROVIDE_RESCUE_INHALER", label: "Rescue Medication", description: "Provide albuterol rescue inhaler for acute symptoms; teach appropriate use technique and spacer/chamber for young children." },
      { step: 6, action: "ASTHMA_ACTION_PLAN", label: "Written Action Plan", description: "Written asthma action plan: green zone (well-controlled), yellow zone (caution), red zone (emergency); laminated for school/home." },
      { step: 7, action: "SCHOOL_AND_SPORTS_COORDINATION", label: "School Communication", description: "Communicate with school: copy of action plan, emergency contact, asthma medication storage at school, PE/sports participation guidelines." },
    ],
  },
  {
    id: "template-peds-developmental-delay",
    name: "Developmental Delay Screening & Early Intervention",
    category: "Pediatrics & Child Health",
    specialty: "Pediatrics",
    description: "Developmental screening (ASQ/MCHAT), multidisciplinary evaluation, cause investigation, and early intervention service referral.",
    triggerEvent: "DEVELOPMENTAL_CONCERN_RAISED",
    conditions: { ageMonths: 24, delayPresent: true },
    steps: [
      { step: 1, action: "ADMINISTER_SCREENING_TOOL", label: "Developmental Screening", description: "Ages & Stages Questionnaire (ASQ) or Bayley Scales of Infant Development to objectively assess developmental milestones." },
      { step: 2, action: "PERFORM_COMPREHENSIVE_HISTORY", label: "Detailed History", description: "Prenatal, birth, neonatal history; developmental milestones timeline; family history of developmental disabilities or autism." },
      { step: 3, action: "PHYSICAL_AND_NEUROLOGIC_EXAM", label: "Clinical Exam", description: "Comprehensive physical exam to identify dysmorphic features, microcephaly, muscle tone abnormalities, reflexes, signs of cerebral palsy." },
      { step: 4, action: "INVESTIGATE_ETIOLOGY", label: "Diagnostic Workup", description: "Newborn screening review, hearing screen, vision exam, metabolic screening (amino acids, organic acids), brain MRI if indicated." },
      { step: 5, action: "REFER_TO_EARLY_INTERVENTION", label: "EI Services Referral", description: "Referral to birth-to-three early intervention (EI) program for developmental therapy: physical, occupational, and speech-language therapy." },
      { step: 6, action: "MULTIDISCIPLINARY_TEAM_CONSULTATION", label: "Specialist Referral", description: "Referrals per findings: developmental pediatrician, genetic counselor, speech-language pathologist, occupational therapist." },
      { step: 7, action: "CREATE_FAMILY_SUPPORT_PLAN", label: "Family Support", description: "Family education, parent coaching, support group connections, financial resources, and individualized family service plan (IFSP) development." },
    ],
  },
  {
    id: "template-peds-vaccine-catch-up",
    name: "Vaccine Catch-Up & Immunization Completion",
    category: "Pediatrics & Child Health",
    specialty: "Pediatrics",
    description: "Assessment of immunization records, missed vaccine identification, accelerated schedule planning, and safety monitoring.",
    triggerEvent: "VACCINE_RECORDS_INCOMPLETE",
    conditions: { completionRate: 85 },
    steps: [
      { step: 1, action: "REVIEW_VACCINE_RECORDS", label: "Records Review", description: "Obtain complete vaccine records (paper, electronic state registry); verify dates and lot numbers for all administered vaccines." },
      { step: 2, action: "IDENTIFY_MISSED_VACCINES", label: "Missing Vaccines", description: "Compare against CDC recommended schedule; identify missing vaccines (routine: MMR, DTaP, varicella; adolescent: HPV, Tdap, meningococcal)." },
      { step: 3, action: "CREATE_ACCELERATED_SCHEDULE", label: "Catch-up Schedule", description: "Develop accelerated catch-up schedule following spacing requirements; most vaccines can be given at same visit if missed." },
      { step: 4, action: "ADDRESS_VACCINE_HESITANCY", label: "Vaccine Counseling", description: "Vaccine risk/benefit discussion addressing safety concerns; evidence-based information on autism/vaccine misconceptions." },
      { step: 5, action: "CHECK_FOR_CONTRAINDICATIONS", label: "Contraindication Review", description: "Screen for true contraindications: severe allergy to vaccine components, severe immunocompromise, thrombocytopenia." },
      { step: 6, action: "ADMINISTER_CATCH_UP_VACCINES", label: "Vaccination Visit", description: "Administer missed vaccines per accelerated schedule; counsel on common side effects (arm soreness, mild fever) and serious adverse events." },
      { step: 7, action: "SCHEDULE_COMPLETION_MONITORING", label: "Follow-up Verification", description: "Schedule follow-up visit to complete remaining vaccines; state registry documentation for school/daycare compliance verification." },
    ],
  },
];
