import type { PrebuiltWorkflowTemplate } from "@/lib/workflow/workflow-definitions";

/** Referral (LRER) and laboratory workflows aligned with emitted API events. */
export const REFERRAL_LABORATORY_WORKFLOW_TEMPLATES: PrebuiltWorkflowTemplate[] = [
  {
    id: "template-referral-intake-routing",
    name: "LRER Referral Intake and Clinical Routing",
    category: "Specialist Consultations & Referrals",
    description: "Routes a new referral to the receiving service, alerts the assigned clinical pool, and confirms submission to the patient.",
    triggerEvent: "SPECIALIST_REFERRAL_CREATED",
    conditions: { status: "pending_review" },
    steps: [
      { step: 1, action: "CREATE_SPECIALIST_REFERRAL", label: "Create Referral Docket", description: "Create a structured referral docket with the clinical reason, urgency, patient, and referring clinician." },
      { step: 2, action: "NOTIFY_SPECIALIST", label: "Notify Receiving Service", description: "Alert the receiving specialty pool that a referral is awaiting clinical review." },
      { step: 3, action: "CREATE_TASK", label: "Create Intake Task", description: "Create an SLA-tracked intake task for the receiving coordinator." },
      { step: 4, action: "SEND_PATIENT_EDUCATION", label: "Confirm Patient Submission", description: "Explain the referral review process and expected next steps in the patient portal." },
    ],
  },
  {
    id: "template-referral-acceptance-scheduling",
    name: "LRER Referral Acceptance and Scheduling",
    category: "Specialist Consultations & Referrals",
    description: "Converts an accepted referral into a scheduled specialist encounter with patient reminders and shared-care preparation.",
    triggerEvent: "SPECIALIST_REFERRAL_ACCEPTED",
    conditions: { status: "accepted" },
    steps: [
      { step: 1, action: "ACCEPT_SPECIALIST_REFERRAL", label: "Record Clinical Acceptance", description: "Record acceptance by the receiving service and preserve the accepting clinician in the audit trail." },
      { step: 2, action: "SCHEDULE_SPECIALIST_APPOINTMENT", label: "Schedule Consultation", description: "Book the earliest appropriate appointment using referral urgency and due date." },
      { step: 3, action: "SEND_APPOINTMENT_REMINDER", label: "Send Appointment Reminder", description: "Send appointment details and preparation instructions to the patient." },
      { step: 4, action: "CREATE_SHARED_CARE_PLAN", label: "Prepare Shared Care Plan", description: "Create a shared care-plan task for the referring and receiving teams." },
    ],
  },
  {
    id: "template-referral-completion-closure",
    name: "LRER Referral Completion and Closed-Loop Handoff",
    category: "Specialist Consultations & Referrals",
    description: "Closes the referral loop by recording the specialist report, notifying the referring clinician, and updating the patient journey.",
    triggerEvent: "SPECIALIST_REFERRAL_COMPLETED",
    conditions: { status: "completed" },
    steps: [
      { step: 1, action: "COMPLETE_SPECIALIST_CONSULT", label: "Record Consultation Report", description: "Attach the signed specialist report and recommendations to the referral record." },
      { step: 2, action: "GENERATE_MDT_SUMMARY", label: "Summarize Recommendations", description: "Generate a concise shared summary when the referral requires multidisciplinary follow-up." },
      { step: 3, action: "NOTIFY_CARE_TEAM", label: "Notify Referring Team", description: "Notify the referring clinician and assigned care team that the consultation is complete." },
      { step: 4, action: "UPDATE_PATIENT_JOURNEY", label: "Advance Care Journey", description: "Advance the patient journey milestone and expose documented next steps in the portal." },
    ],
  },
  {
    id: "template-lab-order-accessioning",
    name: "Laboratory Order to Specimen Accessioning",
    category: "Laboratory & Diagnostics",
    description: "Moves a laboratory order from submission through collection, barcode verification, and laboratory worklist routing.",
    triggerEvent: "LAB_ORDER_SUBMITTED",
    conditions: { orderStatus: "ordered" },
    steps: [
      { step: 1, action: "CREATE_LAB_REQUEST", label: "Route to Laboratory", description: "Send the signed order to the appropriate laboratory worklist." },
      { step: 2, action: "CREATE_TASK", label: "Create Collection Task", description: "Create a collection task with priority, specimen requirements, and turnaround target." },
      { step: 3, action: "RECEIVE_SPECIMEN", label: "Accession Specimen", description: "Record specimen receipt, integrity checks, and accession metadata." },
      { step: 4, action: "VERIFY_BARCODE", label: "Verify Patient Barcode", description: "Match the specimen barcode with the patient and order before analysis begins." },
    ],
  },
  {
    id: "template-lab-routine-result-release",
    name: "Laboratory Routine Result Verification and Release",
    category: "Laboratory & Diagnostics",
    description: "Validates routine results, releases them to the clinical record, and notifies the ordering team and patient through approved channels.",
    triggerEvent: "LAB_RESULT_READY",
    conditions: { isAbnormal: false },
    steps: [
      { step: 1, action: "VALIDATE_LAB_RESULT", label: "Validate Result", description: "Complete technologist validation and quality checks before release." },
      { step: 2, action: "CREATE_CLINICAL_NOTE", label: "Record Result Note", description: "Record the verified result and relevant reference interval in the clinical record." },
      { step: 3, action: "NOTIFY_CARE_TEAM", label: "Notify Ordering Team", description: "Notify the ordering clinician that the result is available for review." },
      { step: 4, action: "SEND_PATIENT_EDUCATION", label: "Release Patient Explanation", description: "Release an accessible explanation without replacing clinician interpretation." },
    ],
  },
  {
    id: "template-lab-critical-value-escalation",
    name: "Laboratory Critical Value Escalation and Acknowledgment",
    category: "Laboratory & Diagnostics",
    description: "Escalates critical laboratory values immediately, records notification attempts, and creates an acknowledgment task for the responsible clinician.",
    triggerEvent: "LAB_RESULT_CRITICAL",
    conditions: { isAbnormal: true, priority: ["urgent", "stat"] },
    steps: [
      { step: 1, action: "FLAG_CRITICAL_LAB_VALUE", label: "Flag Critical Value", description: "Mark the result as critical and prevent it from being lost in routine result queues." },
      { step: 2, action: "ALERT_ATTENDING_PHYSICIAN", label: "Alert Attending Physician", description: "Send an immediate high-priority alert to the ordering or attending clinician." },
      { step: 3, action: "PAGE_ON_CALL_STAFF", label: "Page On-Call Staff", description: "Page the on-call team when the primary clinician does not acknowledge within the configured SLA." },
      { step: 4, action: "CREATE_TASK", label: "Create Acknowledgment Task", description: "Create a traceable task requiring result acknowledgment and documented clinical action." },
      { step: 5, action: "CREATE_AUDIT_LOG", label: "Log Escalation Chain", description: "Record value, notification timestamps, recipients, acknowledgment, and escalation outcome." },
    ],
  },
  {
    id: "template-lab-abnormal-followup",
    name: "Laboratory Abnormal Result Follow-up",
    category: "Laboratory & Diagnostics",
    description: "Creates a clinician review and follow-up plan for abnormal, non-critical laboratory results.",
    triggerEvent: "LAB_RESULT_ABNORMAL",
    conditions: { isAbnormal: true },
    steps: [
      { step: 1, action: "VALIDATE_LAB_RESULT", label: "Validate Abnormal Result", description: "Confirm analytical validity, specimen quality, and reference interval." },
      { step: 2, action: "NOTIFY_SPECIALIST", label: "Notify Relevant Specialist", description: "Route the result to the responsible specialty when the abnormality requires focused review." },
      { step: 3, action: "CREATE_TASK", label: "Create Follow-up Task", description: "Create a due-dated task for interpretation, repeat testing, or treatment adjustment." },
      { step: 4, action: "SUGGEST_BIOCHEMICAL_FOLLOWUP", label: "Suggest Follow-up Testing", description: "Suggest clinically relevant repeat or confirmatory testing for clinician approval." },
      { step: 5, action: "SEND_PATIENT_EDUCATION", label: "Send Follow-up Guidance", description: "Provide patient-facing guidance that a clinician will review the finding and next steps." },
    ],
  },
  {
    id: "template-lab-turnaround-sla",
    name: "Laboratory Turnaround SLA Escalation",
    category: "Laboratory & Diagnostics",
    description: "Monitors delayed laboratory processing and escalates overdue orders to laboratory leadership and the ordering team.",
    triggerEvent: "TASK_OVERDUE",
    conditions: { taskType: "laboratory", slaBreached: true },
    steps: [
      { step: 1, action: "ESCALATE_TASK", label: "Escalate Overdue Work", description: "Escalate the overdue laboratory task to the laboratory supervisor." },
      { step: 2, action: "NOTIFY_CARE_TEAM", label: "Notify Clinical Team", description: "Notify the ordering team that the expected laboratory turnaround has been breached." },
      { step: 3, action: "CREATE_AUDIT_LOG", label: "Log SLA Breach", description: "Record order priority, elapsed time, cause, and corrective action for quality reporting." },
    ],
  },
];
