export interface LaboratoryProtocolItem {
  testCode: string;
  testName: string;
  specimen: string;
  tubeContainer: string;
  collectionProtocol: string;
  handlingStorage: string;
  referenceRangeAdult: string;
  criticalValues: string | null;
  turnaroundTime: string;
  methodology: string;
  category:
    | "Hematology"
    | "Coagulation"
    | "Clinical Chemistry"
    | "Electrolytes & Minerals"
    | "Renal Function"
    | "Hepatic Function"
    | "Enzymes & Cardiac"
    | "Lipid Profile"
    | "Endocrinology & Hormones"
    | "Vitamins & Anemia"
    | "Inflammatory Markers"
    | "Microbiology & Cultures"
    | "Smears & Stains"
    | "Infectious Disease Serology"
    | "Urinalysis & Urine Chem"
    | "Body Fluids (CSF)";
  priceEtb: number;
  isStatAvailable?: boolean;
}

export const LABORATORY_PROTOCOLS_CATALOGUE: LaboratoryProtocolItem[] = [
  // ─── 1. HEMATOLOGY ──────────────────────────────────────────────────────────
  {
    testCode: "CBC",
    testName: "Complete Blood Count",
    specimen: "Whole Blood",
    tubeContainer: "EDTA (Lavender)",
    collectionProtocol: "Mix gently by inversion; do not centrifuge",
    handlingStorage: "Room temp, test within 4 hrs",
    referenceRangeAdult:
      "WBC: 4.0–11.0 ×10⁹/L; RBC: 4.5–5.9 ×10¹²/L; Hgb: 13.0–17.0 g/dL; Hct: 40–50%; Platelets: 150–400 ×10⁹/L",
    criticalValues: "Hgb < 7 g/dL; Platelets < 20 ×10⁹/L; WBC > 30 ×10⁹/L",
    turnaroundTime: "1 hour",
    methodology: "Automated impedance/flow cytometry",
    category: "Hematology",
    priceEtb: 280.0,
    isStatAvailable: true,
  },
  {
    testCode: "HGB",
    testName: "Hemoglobin",
    specimen: "Whole Blood",
    tubeContainer: "EDTA (Lavender)",
    collectionProtocol: "Mix gently",
    handlingStorage: "Room temp",
    referenceRangeAdult: "Male: 13.0–17.0 g/dL; Female: 12.0–15.0 g/dL",
    criticalValues: "< 7 g/dL or > 20 g/dL",
    turnaroundTime: "30 min",
    methodology: "Cyanmethemoglobin or automated",
    category: "Hematology",
    priceEtb: 150.0,
    isStatAvailable: true,
  },
  {
    testCode: "HCT",
    testName: "Hematocrit",
    specimen: "Whole Blood",
    tubeContainer: "EDTA (Lavender)",
    collectionProtocol: "Mix gently",
    handlingStorage: "Room temp",
    referenceRangeAdult: "Male: 40–50%; Female: 36–44%",
    criticalValues: "< 20% or > 60%",
    turnaroundTime: "30 min",
    methodology: "Calculated or spun microhematocrit",
    category: "Hematology",
    priceEtb: 150.0,
    isStatAvailable: true,
  },
  {
    testCode: "PLT",
    testName: "Platelet Count",
    specimen: "Whole Blood",
    tubeContainer: "EDTA (Lavender)",
    collectionProtocol: "Mix gently",
    handlingStorage: "Room temp",
    referenceRangeAdult: "150–400 ×10⁹/L",
    criticalValues: "< 20 ×10⁹/L or > 1000 ×10⁹/L",
    turnaroundTime: "30 min",
    methodology: "Impedance/optical",
    category: "Hematology",
    priceEtb: 160.0,
    isStatAvailable: true,
  },
  {
    testCode: "WBC",
    testName: "White Blood Cell Count",
    specimen: "Whole Blood",
    tubeContainer: "EDTA (Lavender)",
    collectionProtocol: "Mix gently",
    handlingStorage: "Room temp",
    referenceRangeAdult: "4.0–11.0 ×10⁹/L",
    criticalValues: "< 2.0 ×10⁹/L or > 30.0 ×10⁹/L",
    turnaroundTime: "30 min",
    methodology: "Impedance/optical",
    category: "Hematology",
    priceEtb: 150.0,
    isStatAvailable: true,
  },
  {
    testCode: "RETIC",
    testName: "Reticulocyte Count",
    specimen: "Whole Blood",
    tubeContainer: "EDTA (Lavender)",
    collectionProtocol: "Mix gently",
    handlingStorage: "Room temp, test within 6 hrs",
    referenceRangeAdult: "0.5–2.5% of RBC",
    criticalValues: null,
    turnaroundTime: "2 hours",
    methodology: "Supravital stain / flow cytometry",
    category: "Hematology",
    priceEtb: 220.0,
  },
  {
    testCode: "ESR",
    testName: "Erythrocyte Sedimentation Rate",
    specimen: "Whole Blood",
    tubeContainer: "EDTA (Lavender)",
    collectionProtocol: "Keep at room temp, test within 4 hrs",
    handlingStorage: "Room temp",
    referenceRangeAdult: "Male: 0–15 mm/hr; Female: 0–20 mm/hr",
    criticalValues: "> 100 mm/hr",
    turnaroundTime: "1 hour",
    methodology: "Westergren method",
    category: "Hematology",
    priceEtb: 180.0,
  },

  // ─── 2. COAGULATION ─────────────────────────────────────────────────────────
  {
    testCode: "PT",
    testName: "Prothrombin Time",
    specimen: "Plasma",
    tubeContainer: "Sodium Citrate (Blue)",
    collectionProtocol: "Fill to mark, mix, centrifuge within 1 hr",
    handlingStorage: "Plasma separated, test within 4 hrs at RT",
    referenceRangeAdult: "11–13.5 sec; INR: 0.9–1.1",
    criticalValues: "INR > 5",
    turnaroundTime: "1 hour",
    methodology: "Coagulometric",
    category: "Coagulation",
    priceEtb: 240.0,
    isStatAvailable: true,
  },
  {
    testCode: "APTT",
    testName: "Activated Partial Thromboplastin Time",
    specimen: "Plasma",
    tubeContainer: "Sodium Citrate (Blue)",
    collectionProtocol: "Fill to mark, mix, centrifuge within 1 hr",
    handlingStorage: "Plasma separated, test within 4 hrs",
    referenceRangeAdult: "25–35 sec",
    criticalValues: "> 100 sec",
    turnaroundTime: "1 hour",
    methodology: "Coagulometric",
    category: "Coagulation",
    priceEtb: 240.0,
    isStatAvailable: true,
  },
  {
    testCode: "FIB",
    testName: "Fibrinogen",
    specimen: "Plasma",
    tubeContainer: "Sodium Citrate (Blue)",
    collectionProtocol: "Fill to mark, mix, centrifuge within 1 hr",
    handlingStorage: "Plasma separated",
    referenceRangeAdult: "200–400 mg/dL",
    criticalValues: "< 100 mg/dL",
    turnaroundTime: "2 hours",
    methodology: "Clauss method",
    category: "Coagulation",
    priceEtb: 320.0,
  },
  {
    testCode: "D-DIMER",
    testName: "D-Dimer",
    specimen: "Plasma",
    tubeContainer: "Sodium Citrate (Blue)",
    collectionProtocol: "Fill to mark, mix, centrifuge within 1 hr",
    handlingStorage: "Plasma separated, test within 4 hrs",
    referenceRangeAdult: "< 0.5 µg/mL FEU",
    criticalValues: null,
    turnaroundTime: "1 hour",
    methodology: "Immunoturbidimetric",
    category: "Coagulation",
    priceEtb: 450.0,
    isStatAvailable: true,
  },

  // ─── 3. GLUCOSE & DIABETES ──────────────────────────────────────────────────
  {
    testCode: "GLU",
    testName: "Glucose, Fasting",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Fasting 8–10 hrs; no alcohol 24 hrs",
    handlingStorage: "Serum separated, stable 24 hrs at 4°C",
    referenceRangeAdult: "70–99 mg/dL",
    criticalValues: "< 40 mg/dL or > 500 mg/dL",
    turnaroundTime: "1 hour",
    methodology: "Hexokinase / GPO",
    category: "Clinical Chemistry",
    priceEtb: 140.0,
    isStatAvailable: true,
  },
  {
    testCode: "GLUR",
    testName: "Glucose, Random",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting; draw at any time",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "70–140 mg/dL",
    criticalValues: "< 40 mg/dL or > 500 mg/dL",
    turnaroundTime: "1 hour",
    methodology: "Hexokinase / GPO",
    category: "Clinical Chemistry",
    priceEtb: 120.0,
    isStatAvailable: true,
  },
  {
    testCode: "HBA1C",
    testName: "Hemoglobin A1c",
    specimen: "Whole Blood",
    tubeContainer: "EDTA (Lavender)",
    collectionProtocol: "No fasting",
    handlingStorage: "Refrigerate if delay > 24 hrs",
    referenceRangeAdult: "4.0–5.6% (NGSP)",
    criticalValues: "> 15%",
    turnaroundTime: "4 hours",
    methodology: "HPLC / Immunoassay",
    category: "Clinical Chemistry",
    priceEtb: 380.0,
  },

  // ─── 4. RENAL FUNCTION & ELECTROLYTES ───────────────────────────────────────
  {
    testCode: "BUN",
    testName: "Blood Urea Nitrogen",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "7–20 mg/dL",
    criticalValues: "> 100 mg/dL",
    turnaroundTime: "1 hour",
    methodology: "Urease/GLDH",
    category: "Renal Function",
    priceEtb: 160.0,
  },
  {
    testCode: "CREAT",
    testName: "Creatinine",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Male: 0.7–1.3 mg/dL; Female: 0.6–1.1 mg/dL",
    criticalValues: "> 8 mg/dL",
    turnaroundTime: "1 hour",
    methodology: "Jaffe / Enzymatic",
    category: "Renal Function",
    priceEtb: 160.0,
    isStatAvailable: true,
  },
  {
    testCode: "EGFR",
    testName: "Estimated GFR (calculated)",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Use creatinine, age, sex",
    handlingStorage: "Calculated",
    referenceRangeAdult: "≥ 90 mL/min/1.73m²",
    criticalValues: "< 15 mL/min/1.73m²",
    turnaroundTime: "1 hour",
    methodology: "CKD-EPI equation",
    category: "Renal Function",
    priceEtb: 160.0,
  },
  {
    testCode: "NA",
    testName: "Sodium",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting; avoid hemolysis",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "135–145 mmol/L",
    criticalValues: "< 120 mmol/L or > 160 mmol/L",
    turnaroundTime: "1 hour",
    methodology: "Ion-selective electrode",
    category: "Electrolytes & Minerals",
    priceEtb: 160.0,
    isStatAvailable: true,
  },
  {
    testCode: "K",
    testName: "Potassium",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Avoid hemolysis; do not leave on cells",
    handlingStorage: "Serum separated within 2 hrs",
    referenceRangeAdult: "3.5–5.1 mmol/L",
    criticalValues: "< 2.8 mmol/L or > 6.5 mmol/L",
    turnaroundTime: "1 hour",
    methodology: "Ion-selective electrode",
    category: "Electrolytes & Minerals",
    priceEtb: 160.0,
    isStatAvailable: true,
  },
  {
    testCode: "CL",
    testName: "Chloride",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "98–107 mmol/L",
    criticalValues: "< 80 mmol/L or > 120 mmol/L",
    turnaroundTime: "1 hour",
    methodology: "Ion-selective electrode",
    category: "Electrolytes & Minerals",
    priceEtb: 150.0,
  },
  {
    testCode: "CO2",
    testName: "Bicarbonate",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting; avoid air exposure",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "22–29 mmol/L",
    criticalValues: "< 10 mmol/L or > 40 mmol/L",
    turnaroundTime: "1 hour",
    methodology: "Enzymatic / ISE",
    category: "Electrolytes & Minerals",
    priceEtb: 170.0,
    isStatAvailable: true,
  },
  {
    testCode: "CA",
    testName: "Calcium",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "8.5–10.5 mg/dL",
    criticalValues: "< 6.0 mg/dL or > 13.0 mg/dL",
    turnaroundTime: "1 hour",
    methodology: "Arsenazo III / CPC",
    category: "Electrolytes & Minerals",
    priceEtb: 170.0,
  },
  {
    testCode: "MG",
    testName: "Magnesium",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "1.7–2.2 mg/dL",
    criticalValues: "< 1.0 mg/dL or > 5.0 mg/dL",
    turnaroundTime: "1 hour",
    methodology: "Colorimetric",
    category: "Electrolytes & Minerals",
    priceEtb: 190.0,
  },
  {
    testCode: "PHOS",
    testName: "Phosphorus",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting; avoid hemolysis",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "2.5–4.5 mg/dL",
    criticalValues: "< 1.0 mg/dL or > 9.0 mg/dL",
    turnaroundTime: "1 hour",
    methodology: "Molybdate UV",
    category: "Electrolytes & Minerals",
    priceEtb: 180.0,
  },

  // ─── 5. HEPATIC FUNCTION & PROTEINS ─────────────────────────────────────────
  {
    testCode: "ALB",
    testName: "Albumin",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "3.5–5.2 g/dL",
    criticalValues: "< 2.0 g/dL",
    turnaroundTime: "1 hour",
    methodology: "BCG dye binding",
    category: "Hepatic Function",
    priceEtb: 160.0,
  },
  {
    testCode: "TP",
    testName: "Total Protein",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "6.4–8.3 g/dL",
    criticalValues: "< 4.0 g/dL",
    turnaroundTime: "1 hour",
    methodology: "Biuret",
    category: "Hepatic Function",
    priceEtb: 160.0,
  },
  {
    testCode: "TBILI",
    testName: "Total Bilirubin",
    specimen: "Serum",
    tubeContainer: "SST (protect from light)",
    collectionProtocol: "No fasting; protect from light",
    handlingStorage: "Serum separated, protect from light",
    referenceRangeAdult: "0.1–1.2 mg/dL",
    criticalValues: "> 15 mg/dL",
    turnaroundTime: "2 hours",
    methodology: "Diazo / Vanadate",
    category: "Hepatic Function",
    priceEtb: 170.0,
  },
  {
    testCode: "DBILI",
    testName: "Direct Bilirubin",
    specimen: "Serum",
    tubeContainer: "SST (protect from light)",
    collectionProtocol: "No fasting; protect from light",
    handlingStorage: "Serum separated, protect from light",
    referenceRangeAdult: "0.0–0.3 mg/dL",
    criticalValues: "> 10 mg/dL",
    turnaroundTime: "2 hours",
    methodology: "Diazo",
    category: "Hepatic Function",
    priceEtb: 170.0,
  },
  {
    testCode: "ALP",
    testName: "Alkaline Phosphatase",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "44–147 IU/L",
    criticalValues: "> 1000 IU/L",
    turnaroundTime: "2 hours",
    methodology: "pNPP kinetic",
    category: "Hepatic Function",
    priceEtb: 190.0,
  },
  {
    testCode: "AST",
    testName: "Aspartate Aminotransferase",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Avoid hemolysis",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "10–40 IU/L",
    criticalValues: "> 1000 IU/L",
    turnaroundTime: "2 hours",
    methodology: "IFCC kinetic",
    category: "Hepatic Function",
    priceEtb: 180.0,
  },
  {
    testCode: "ALT",
    testName: "Alanine Aminotransferase",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Avoid hemolysis",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "7–56 IU/L",
    criticalValues: "> 1000 IU/L",
    turnaroundTime: "2 hours",
    methodology: "IFCC kinetic",
    category: "Hepatic Function",
    priceEtb: 180.0,
  },
  {
    testCode: "GGT",
    testName: "Gamma-Glutamyl Transferase",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Male: 8–61 IU/L; Female: 5–36 IU/L",
    criticalValues: "> 500 IU/L",
    turnaroundTime: "2 hours",
    methodology: "Kinetic colorimetric",
    category: "Hepatic Function",
    priceEtb: 220.0,
  },

  // ─── 6. ENZYMES & CARDIAC BIOMARKERS ────────────────────────────────────────
  {
    testCode: "AMY",
    testName: "Amylase",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "23–85 IU/L",
    criticalValues: "> 500 IU/L",
    turnaroundTime: "2 hours",
    methodology: "Enzymatic",
    category: "Enzymes & Cardiac",
    priceEtb: 240.0,
  },
  {
    testCode: "LIPASE",
    testName: "Lipase",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "0–160 IU/L",
    criticalValues: "> 1000 IU/L",
    turnaroundTime: "2 hours",
    methodology: "Enzymatic colorimetric",
    category: "Enzymes & Cardiac",
    priceEtb: 260.0,
  },
  {
    testCode: "LDH",
    testName: "Lactate Dehydrogenase",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Avoid hemolysis",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "140–280 IU/L",
    criticalValues: "> 1000 IU/L",
    turnaroundTime: "2 hours",
    methodology: "Lactate to pyruvate",
    category: "Enzymes & Cardiac",
    priceEtb: 210.0,
  },
  {
    testCode: "CK",
    testName: "Creatine Kinase",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Avoid hemolysis",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Male: 39–308 IU/L; Female: 26–192 IU/L",
    criticalValues: "> 5000 IU/L",
    turnaroundTime: "2 hours",
    methodology: "IFCC kinetic",
    category: "Enzymes & Cardiac",
    priceEtb: 250.0,
    isStatAvailable: true,
  },

  // ─── 7. LIPID PROFILE ───────────────────────────────────────────────────────
  {
    testCode: "CHOL",
    testName: "Total Cholesterol",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Fasting 12 hrs preferred",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "< 200 mg/dL",
    criticalValues: "> 500 mg/dL",
    turnaroundTime: "4 hours",
    methodology: "Enzymatic",
    category: "Lipid Profile",
    priceEtb: 160.0,
  },
  {
    testCode: "TRIG",
    testName: "Triglycerides",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Fasting 12 hrs",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "< 150 mg/dL",
    criticalValues: "> 1000 mg/dL",
    turnaroundTime: "4 hours",
    methodology: "Enzymatic",
    category: "Lipid Profile",
    priceEtb: 170.0,
  },
  {
    testCode: "HDL",
    testName: "HDL Cholesterol",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Fasting not required",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Male: > 40 mg/dL; Female: > 50 mg/dL",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Direct homogeneous",
    category: "Lipid Profile",
    priceEtb: 180.0,
  },
  {
    testCode: "LDL",
    testName: "LDL Cholesterol (calculated)",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Fasting 12 hrs",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "< 100 mg/dL (optimal)",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Friedewald equation (if TRIG < 400)",
    category: "Lipid Profile",
    priceEtb: 180.0,
  },

  // ─── 8. URIC ACID, IRON & INFLAMMATION ──────────────────────────────────────
  {
    testCode: "URIC",
    testName: "Uric Acid",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Male: 3.7–8.6 mg/dL; Female: 2.5–6.0 mg/dL",
    criticalValues: "> 12 mg/dL",
    turnaroundTime: "2 hours",
    methodology: "Uricase",
    category: "Clinical Chemistry",
    priceEtb: 160.0,
  },
  {
    testCode: "IRON",
    testName: "Iron",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Morning draw preferred; avoid hemolysis",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "60–170 µg/dL",
    criticalValues: "> 500 µg/dL",
    turnaroundTime: "4 hours",
    methodology: "Ferrozine",
    category: "Vitamins & Anemia",
    priceEtb: 220.0,
  },
  {
    testCode: "FERR",
    testName: "Ferritin",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Male: 20–250 ng/mL; Female: 10–120 ng/mL",
    criticalValues: "< 10 ng/mL",
    turnaroundTime: "4 hours",
    methodology: "Immunoturbidimetric",
    category: "Vitamins & Anemia",
    priceEtb: 320.0,
  },
  {
    testCode: "CRP",
    testName: "C-Reactive Protein",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "< 5 mg/L",
    criticalValues: "> 200 mg/L",
    turnaroundTime: "2 hours",
    methodology: "Immunoturbidimetric",
    category: "Inflammatory Markers",
    priceEtb: 250.0,
    isStatAvailable: true,
  },

  // ─── 9. ENDOCRINOLOGY & HORMONES ────────────────────────────────────────────
  {
    testCode: "TSH",
    testName: "Thyroid Stimulating Hormone",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "0.4–4.0 µIU/mL",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Electrochemiluminescence",
    category: "Endocrinology & Hormones",
    priceEtb: 320.0,
  },
  {
    testCode: "FT4",
    testName: "Free Thyroxine",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "0.8–1.8 ng/dL",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Electrochemiluminescence",
    category: "Endocrinology & Hormones",
    priceEtb: 340.0,
  },
  {
    testCode: "FT3",
    testName: "Free Triiodothyronine",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "2.3–4.2 pg/mL",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Electrochemiluminescence",
    category: "Endocrinology & Hormones",
    priceEtb: 340.0,
  },
  {
    testCode: "CORT",
    testName: "Cortisol (AM)",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Draw at 8 AM; patient rested",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "6–23 µg/dL",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Immunoassay",
    category: "Endocrinology & Hormones",
    priceEtb: 380.0,
  },
  {
    testCode: "PROL",
    testName: "Prolactin",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Morning draw; avoid stress",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Male: 2–18 ng/mL; Female: 2–29 ng/mL",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Immunoassay",
    category: "Endocrinology & Hormones",
    priceEtb: 350.0,
  },
  {
    testCode: "TESTO",
    testName: "Testosterone",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Morning draw (7–10 AM)",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Male: 300–1000 ng/dL",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Immunoassay",
    category: "Endocrinology & Hormones",
    priceEtb: 400.0,
  },
  {
    testCode: "E2",
    testName: "Estradiol",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Cycle-dependent; note LMP",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Follicular: 20–150 pg/mL",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Immunoassay",
    category: "Endocrinology & Hormones",
    priceEtb: 400.0,
  },
  {
    testCode: "FSH",
    testName: "Follicle-Stimulating Hormone",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Cycle-dependent",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Male: 1.5–12.4 IU/L",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Immunoassay",
    category: "Endocrinology & Hormones",
    priceEtb: 350.0,
  },
  {
    testCode: "LH",
    testName: "Luteinizing Hormone",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "Cycle-dependent",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Male: 1.8–8.6 IU/L",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Immunoassay",
    category: "Endocrinology & Hormones",
    priceEtb: 350.0,
  },
  {
    testCode: "PSA",
    testName: "Prostate-Specific Antigen",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No ejaculation 24–48 hrs prior",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "< 4.0 ng/mL",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Immunoassay",
    category: "Endocrinology & Hormones",
    priceEtb: 380.0,
  },

  // ─── 10. VITAMINS ───────────────────────────────────────────────────────────
  {
    testCode: "VITD",
    testName: "Vitamin D (25-OH)",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Protect from light",
    referenceRangeAdult: "30–100 ng/mL",
    criticalValues: null,
    turnaroundTime: "24 hours",
    methodology: "LC-MS/MS / Immunoassay",
    category: "Vitamins & Anemia",
    priceEtb: 550.0,
  },
  {
    testCode: "B12",
    testName: "Vitamin B12",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Protect from light",
    referenceRangeAdult: "200–900 pg/mL",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Electrochemiluminescence",
    category: "Vitamins & Anemia",
    priceEtb: 420.0,
  },
  {
    testCode: "FOLATE",
    testName: "Folate",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Protect from light",
    referenceRangeAdult: "3–17 ng/mL",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Electrochemiluminescence",
    category: "Vitamins & Anemia",
    priceEtb: 400.0,
  },

  // ─── 11. MICROBIOLOGY CULTURES & STAINS ─────────────────────────────────────
  {
    testCode: "UAC",
    testName: "Urine Culture & Sensitivity",
    specimen: "Midstream Urine",
    tubeContainer: "Sterile container",
    collectionProtocol: "Clean catch; first morning; refrigerate if delay",
    handlingStorage: "Refrigerate at 4°C within 1 hr",
    referenceRangeAdult: "Negative (No growth)",
    criticalValues: null,
    turnaroundTime: "48–72 hours",
    methodology: "Culture on agar",
    category: "Microbiology & Cultures",
    priceEtb: 380.0,
  },
  {
    testCode: "BLC",
    testName: "Blood Culture",
    specimen: "Blood (aerobic/anaerobic)",
    tubeContainer: "Blood culture bottles",
    collectionProtocol: "Aseptic collection; 2 sets from different sites",
    handlingStorage: "Incubate at 37°C; transport immediately",
    referenceRangeAdult: "Negative",
    criticalValues: null,
    turnaroundTime: "5 days",
    methodology: "Automated blood culture system",
    category: "Microbiology & Cultures",
    priceEtb: 550.0,
  },
  {
    testCode: "THR",
    testName: "Throat Swab C/S",
    specimen: "Throat swab",
    tubeContainer: "Amies transport medium",
    collectionProtocol: "Swab tonsils/back of throat; avoid tongue",
    handlingStorage: "Transport at RT; process within 24 hrs",
    referenceRangeAdult: "Negative for Group A Strep",
    criticalValues: null,
    turnaroundTime: "48 hours",
    methodology: "Culture on blood agar",
    category: "Microbiology & Cultures",
    priceEtb: 340.0,
  },
  {
    testCode: "STOOLC",
    testName: "Stool Culture",
    specimen: "Stool",
    tubeContainer: "Sterile container",
    collectionProtocol: "Fresh sample; no preservative",
    handlingStorage: "Transport at RT; process within 2 hrs",
    referenceRangeAdult: "Negative for Salmonella, Shigella, Campylobacter",
    criticalValues: null,
    turnaroundTime: "48–72 hours",
    methodology: "Selective media",
    category: "Microbiology & Cultures",
    priceEtb: 360.0,
  },
  {
    testCode: "SPUTUMC",
    testName: "Sputum Culture",
    specimen: "Sputum",
    tubeContainer: "Sterile container",
    collectionProtocol: "Deep cough; first morning; rinse mouth with water first",
    handlingStorage: "Refrigerate if delay",
    referenceRangeAdult: "Normal flora",
    criticalValues: null,
    turnaroundTime: "48–72 hours",
    methodology: "Culture + Gram stain",
    category: "Microbiology & Cultures",
    priceEtb: 380.0,
  },
  {
    testCode: "GRAM",
    testName: "Gram Stain",
    specimen: "Various",
    tubeContainer: "Slide/container",
    collectionProtocol: "As per source; smear prepared immediately",
    handlingStorage: "Heat fix or transport",
    referenceRangeAdult: "No organisms",
    criticalValues: null,
    turnaroundTime: "1 hour",
    methodology: "Gram staining",
    category: "Smears & Stains",
    priceEtb: 150.0,
    isStatAvailable: true,
  },
  {
    testCode: "AFB",
    testName: "Acid-Fast Bacilli (TB)",
    specimen: "Sputum (3 samples)",
    tubeContainer: "Sterile container",
    collectionProtocol: "Early morning on consecutive days; collect 5–10 ml",
    handlingStorage: "Refrigerate if delay",
    referenceRangeAdult: "Negative",
    criticalValues: null,
    turnaroundTime: "Smear: 24 hrs; culture: 6 weeks",
    methodology: "Ziehl-Neelsen / fluorescence",
    category: "Smears & Stains",
    priceEtb: 220.0,
  },
  {
    testCode: "MALARIA",
    testName: "Malaria Smear",
    specimen: "Whole Blood",
    tubeContainer: "EDTA (Lavender)",
    collectionProtocol: "Thick/thin smear made at bedside; collect during fever spike",
    handlingStorage: "Transport at RT",
    referenceRangeAdult: "Negative",
    criticalValues: null,
    turnaroundTime: "1 hour",
    methodology: "Giemsa stain",
    category: "Smears & Stains",
    priceEtb: 160.0,
    isStatAvailable: true,
  },

  // ─── 12. INFECTIOUS DISEASE SEROLOGY ────────────────────────────────────────
  {
    testCode: "HBSAG",
    testName: "Hepatitis B Surface Antigen",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Non-reactive",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "ELISA / CLIA",
    category: "Infectious Disease Serology",
    priceEtb: 250.0,
  },
  {
    testCode: "HCV",
    testName: "Hepatitis C Antibody",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Non-reactive",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "ELISA / CLIA",
    category: "Infectious Disease Serology",
    priceEtb: 280.0,
  },
  {
    testCode: "HIV",
    testName: "HIV Rapid Test / ELISA",
    specimen: "Serum/Whole Blood",
    tubeContainer: "SST/EDTA",
    collectionProtocol: "Pre/post-test counseling",
    handlingStorage: "Serum separated; RT for rapid",
    referenceRangeAdult: "Non-reactive",
    criticalValues: null,
    turnaroundTime: "30 min (rapid) / 4 hrs (ELISA)",
    methodology: "Immunochromatography / ELISA",
    category: "Infectious Disease Serology",
    priceEtb: 200.0,
    isStatAvailable: true,
  },
  {
    testCode: "VDRL",
    testName: "Syphilis (VDRL/RPR)",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "Non-reactive",
    criticalValues: null,
    turnaroundTime: "4 hours",
    methodology: "Flocculation",
    category: "Infectious Disease Serology",
    priceEtb: 180.0,
  },
  {
    testCode: "WIDAL",
    testName: "Widal Test (Typhoid)",
    specimen: "Serum",
    tubeContainer: "SST (Gold)",
    collectionProtocol: "No fasting; acute & convalescent samples",
    handlingStorage: "Serum separated",
    referenceRangeAdult: "< 1:160",
    criticalValues: null,
    turnaroundTime: "24 hours",
    methodology: "Agglutination",
    category: "Infectious Disease Serology",
    priceEtb: 200.0,
  },

  // ─── 13. URINALYSIS & BODY FLUIDS ───────────────────────────────────────────
  {
    testCode: "UAM",
    testName: "Urinalysis (Complete)",
    specimen: "Urine (midstream)",
    tubeContainer: "Sterile cup",
    collectionProtocol: "Clean catch; first morning preferred",
    handlingStorage: "Test within 1–2 hrs or refrigerate",
    referenceRangeAdult:
      "Color: Yellow; pH: 4.5–8.0; Protein: Neg; Glucose: Neg; Ketones: Neg; Blood: Neg; Leukocytes: Neg; Nitrites: Neg",
    criticalValues: null,
    turnaroundTime: "30 min",
    methodology: "Dipstick + microscopy",
    category: "Urinalysis & Urine Chem",
    priceEtb: 150.0,
    isStatAvailable: true,
  },
  {
    testCode: "UPRO",
    testName: "24-hour Urine Protein",
    specimen: "24-hour urine",
    tubeContainer: "Large container",
    collectionProtocol: "Collect all urine for 24 hrs; keep refrigerated during collection",
    handlingStorage: "Refrigerate",
    referenceRangeAdult: "< 150 mg/24 hr",
    criticalValues: null,
    turnaroundTime: "24 hours",
    methodology: "Colorimetric / turbidimetric",
    category: "Urinalysis & Urine Chem",
    priceEtb: 250.0,
  },
  {
    testCode: "UCA",
    testName: "Urine Calcium",
    specimen: "24-hour urine",
    tubeContainer: "Acid-washed container",
    collectionProtocol: "Collect with HCl preservative",
    handlingStorage: "Refrigerate",
    referenceRangeAdult: "100–300 mg/24 hr",
    criticalValues: null,
    turnaroundTime: "24 hours",
    methodology: "Arsenazo III",
    category: "Urinalysis & Urine Chem",
    priceEtb: 260.0,
  },
  {
    testCode: "UCREAT",
    testName: "Urine Creatinine",
    specimen: "Random urine",
    tubeContainer: "Sterile cup",
    collectionProtocol: "No preservative",
    handlingStorage: "Refrigerate",
    referenceRangeAdult: "20–320 mg/dL (varies)",
    criticalValues: null,
    turnaroundTime: "1 hour",
    methodology: "Jaffe / Enzymatic",
    category: "Urinalysis & Urine Chem",
    priceEtb: 180.0,
  },
  {
    testCode: "CSF",
    testName: "Cerebrospinal Fluid Analysis",
    specimen: "CSF",
    tubeContainer: "Sterile tubes (4)",
    collectionProtocol:
      "Aseptic lumbar puncture; collect 1 ml per tube; tube 1 for chemistry/serology, tube 2 for microbiology, tube 3 for cell count, tube 4 for cytology",
    handlingStorage: "Transport immediately on ice",
    referenceRangeAdult: "WBC < 5/µL; Glucose ~ 2/3 serum; Protein 15–45 mg/dL",
    criticalValues: null,
    turnaroundTime: "1 hour (cell count/chem); 48 hrs (culture)",
    methodology: "Manual cell count, protein/sugar",
    category: "Body Fluids (CSF)",
    priceEtb: 650.0,
    isStatAvailable: true,
  },
  {
    testCode: "PT/INR",
    testName: "Prothrombin Time/INR",
    specimen: "Plasma",
    tubeContainer: "Sodium Citrate (Blue)",
    collectionProtocol: "Fill to mark; mix; centrifuge",
    handlingStorage: "Plasma separated",
    referenceRangeAdult: "11–13.5 sec; INR 0.9–1.1",
    criticalValues: "INR > 5",
    turnaroundTime: "1 hour",
    methodology: "Coagulometric",
    category: "Coagulation",
    priceEtb: 250.0,
    isStatAvailable: true,
  },
];
