import type { Pool } from "mysql2/promise";

/**
 * Minimal, idempotent DDL that the authentication flow depends on.
 *
 * This is deliberately kept separate from the large schema block in
 * migrate-and-seed.ts: that block runs as a single statement batch, so one
 * failure anywhere in it silently skips everything after it. Login must not
 * depend on that. Each statement here is executed on its own.
 *
 * MySQL note: id/user_id are VARCHAR(36) UUIDs generated by the application
 * (see src/db/schema.ts $defaultFn) rather than a database-side default,
 * since MySQL disallows non-deterministic functions like UUID() in a column
 * DEFAULT. The foreign key is a separate constraint clause because MySQL
 * silently ignores an inline `REFERENCES` on a column definition.
 */
export const AUTH_SCHEMA_STATEMENTS: readonly string[] = [
  // MySQL 8 does not support `ADD COLUMN IF NOT EXISTS`; ensureAuthSchemaWithClient
  // below tolerates ER_DUP_FIELDNAME (1060) when the column is already there.
  `ALTER TABLE users ADD COLUMN national_id TEXT`,
  `ALTER TABLE users ADD COLUMN phone TEXT`,
  `ALTER TABLE users ADD COLUMN is_admin_granted_by_super_admin BOOLEAN DEFAULT FALSE NOT NULL`,
  `ALTER TABLE users ADD COLUMN is_active BOOLEAN DEFAULT TRUE NOT NULL`,
  `CREATE TABLE IF NOT EXISTS auth_sessions (
      id VARCHAR(36) PRIMARY KEY,
      user_id VARCHAR(36) NOT NULL,
      token_hash VARCHAR(255) NOT NULL UNIQUE,
      expires_at DATETIME NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
      last_seen_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
      ip_address TEXT,
      user_agent TEXT,
      CONSTRAINT auth_sessions_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      INDEX auth_sessions_user_id_idx (user_id),
      INDEX auth_sessions_expires_at_idx (expires_at)
  )`,
];

/**
 * Run the auth DDL with a raw mysql2 pool (used by migrations/seeding).
 * Returns false without doing anything when the `users` table does not exist
 * yet (fresh database): the main schema block creates it, and this is called
 * again afterwards.
 */
export async function ensureAuthSchemaWithClient(client: Pool): Promise<boolean> {
  const [rows] = await client.query<any[]>(
    `SELECT COUNT(*) AS count FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = 'users'`
  );
  const exists = Number(rows[0]?.count ?? 0) > 0;
  if (!exists) return false;
  for (const statement of AUTH_SCHEMA_STATEMENTS) {
    try {
      await client.query(statement);
    } catch (err: any) {
      // MySQL raises ER_DUP_FIELDNAME (1060) for a column added by a prior
      // run even with IF NOT EXISTS on some 8.0 patch levels, and
      // ER_TABLE_EXISTS_ERROR (1050) is likewise harmless here.
      if (err?.errno !== 1060 && err?.errno !== 1050) throw err;
    }
  }
  return true;
}
