import type { Pool } from "mysql2/promise";
import fs from "fs";
import path from "path";
import { seedDemoAccounts } from "./demo-accounts";
import { ensureAuthSchemaWithClient } from "./auth-schema";
import { PHARMACY_MASTER_CATALOGUE } from "../lib/catalogue/pharmacy-master-catalogue";
import { LABORATORY_PROTOCOLS_CATALOGUE } from "../lib/catalogue/laboratory-protocols-catalogue";

export type DatabaseInitializationOptions = {
  seed?: boolean;
};

// Idempotency-related MySQL error numbers: re-running DDL that already
// applied (table/column/constraint already exists) is expected and safe to
// ignore, since the generated migration is re-applied on every boot.
const IGNORABLE_DDL_ERRNOS = new Set([
  1050, // ER_TABLE_EXISTS_ERROR
  1060, // ER_DUP_FIELDNAME
  1061, // ER_DUP_KEYNAME
  1826, // ER_FK_DUP_NAME / duplicate foreign key constraint
  1022, // ER_DUP_KEY
]);

/**
 * The table DDL itself is generated by drizzle-kit from src/db/schema.ts
 * (`bun run db:generate`, committed under drizzle/) rather than hand-written
 * here, so the two never drift: this just applies whatever drizzle-kit last
 * emitted, statement by statement, tolerating "already exists" errors so it
 * is safe to run on every boot against an already-migrated database.
 */
async function applyGeneratedMigrations(client: Pool): Promise<void> {
  const migrationsDir = path.resolve(process.cwd(), "drizzle");
  if (!fs.existsSync(migrationsDir)) {
    console.warn("[NiniMed DB] No drizzle/ migrations folder found; skipping schema apply.");
    return;
  }
  const files = fs
    .readdirSync(migrationsDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();

  for (const file of files) {
    const sql = fs.readFileSync(path.join(migrationsDir, file), "utf8");
    const statements = sql
      .split("--> statement-breakpoint")
      .map((s) => s.trim())
      .filter(Boolean);

    for (const statement of statements) {
      try {
        await client.query(statement);
      } catch (err: any) {
        if (!IGNORABLE_DDL_ERRNOS.has(err?.errno)) {
          console.error(`[NiniMed DB] Migration statement failed (${file}):`, err?.message || err);
          if (process.env.NINIMED_STRICT_DB === "true") throw err;
        }
      }
    }
  }
}

export async function ensureDatabaseInitialized(
  client: Pool,
  options: DatabaseInitializationOptions = {},
) {
  const shouldSeed = options.seed ?? true;
  try {
    console.log("⚡ Checking and synchronizing NiniMed MySQL schema...");

    // 1. Authentication tables/columns first. Login must not depend on the
    //    full schema apply below having run to completion. On a fresh
    //    database `users` does not exist yet; the pass is repeated after.
    const syncAuthSchema = async () => {
      try {
        await ensureAuthSchemaWithClient(client);
      } catch (authErr) {
        console.error("Auth schema synchronization failed:", authErr);
        if (process.env.NINIMED_STRICT_DB === "true") throw authErr;
      }
    };
    await syncAuthSchema();

    // 2. Apply the full generated schema (all tables, indexes, foreign keys).
    await applyGeneratedMigrations(client);

    console.log("✅ MySQL schema verification complete (all tables, pricing, pharmacy and lab protocols confirmed).");

    // 3. Auth schema again, now that `users` is guaranteed to exist.
    await syncAuthSchema();

    if (!shouldSeed) {
      console.log("ℹ️ Seed data disabled for this database operation.");
      return;
    }

    // 4. Check if seed data exists before inserting.
    const [[orgCheck]] = await client.query<any[]>(`SELECT COUNT(*) as count FROM organizations`);

    if (orgCheck && Number(orgCheck.count) > 0) {
      console.log("ℹ️ Database already has seed organizations. Skipping initial seed insert.");
      await syncComprehensiveCatalogues(client);
      await seedDemoAccounts(client);
      return;
    }

    console.log("🌱 Inserting initial seed data for NiniMed Health System...");
    await seedInitialData(client);
    await syncComprehensiveCatalogues(client);
    await seedDemoAccounts(client);
  } catch (error: any) {
    if (error?.code === "ECONNREFUSED" || error?.message?.includes("ECONNREFUSED")) {
      console.log("ℹ️ Database connection not ready yet. Schema synchronization will occur upon container connection.");
    } else {
      console.error("Database initialization note:", error?.message || error);
      if (process.env.NINIMED_STRICT_DB === "true") {
        throw error;
      }
    }
  }
}

/**
 * One-time bootstrap data for a brand-new database: the default tenant, a
 * fallback super admin, and a small set of illustrative catalogue/demo rows.
 * All inserts are idempotent (INSERT IGNORE / ON DUPLICATE KEY UPDATE) so
 * re-running this is harmless.
 */
async function seedInitialData(client: Pool): Promise<void> {
  await client.query(`
    INSERT IGNORE INTO organizations (id, name, slug, status, settings)
    VALUES (
        '00000000-0000-0000-0000-000000000001',
        'NiniMed Enterprise Health System',
        'org-Nini',
        'active',
        '{"theme": "dark", "multitenancy": true, "auditLevel": "21CFR11"}'
    );
  `);

  await client.query(`
    INSERT IGNORE INTO facilities (id, organization_id, name, address, timezone)
    VALUES (
        '00000000-0000-0000-0000-000000000002',
        '00000000-0000-0000-0000-000000000001',
        'NiniMed Clinic& Clinic',
        'Bole Sub-City, Addis Ababa, Ethiopia',
        'Africa/Addis_Ababa'
    );
  `);

  // Clean up previous demo users and demo patient records
  await client.query(`
    DELETE FROM users WHERE email != 'admin@Ninimed.org' AND email != 'abebetadesse1@gmail.com' AND (
      email LIKE '%@Ninimed.org' OR
      email LIKE '%@patient.Nini.org' OR
      email LIKE '%@Ninipharm.org' OR
      email LIKE '%@Ninirehab.org' OR
      email LIKE '%@Nininutrition.org' OR
      email LIKE '%@Ninisocial.org' OR
      email LIKE '%@Ninilabs.org'
    );
  `);
  await client.query(`DELETE FROM patients WHERE mrn = 'MRN-89210';`);
  await client.query(`DELETE FROM family_groups WHERE name = 'The Vance Family';`);

  // Seed Primary Super Admin User (password: Admin@2026!)
  await client.query(`
    INSERT INTO users (id, organization_id, email, password_hash, full_name, role, department, is_admin_granted_by_super_admin, is_active, created_at, updated_at)
    VALUES (
        '00000000-0000-0000-0000-000000000099',
        '00000000-0000-0000-0000-000000000001',
        'admin@Ninimed.org',
        SHA2('Admin@2026!', 256),
        'System Super Administrator',
        'system_admin',
        'Enterprise IT & Clinical Governance',
        TRUE,
        TRUE,
        NOW(),
        NOW()
    )
    ON DUPLICATE KEY UPDATE
        role = 'system_admin',
        full_name = 'System Super Administrator',
        password_hash = SHA2('Admin@2026!', 256),
        is_admin_granted_by_super_admin = TRUE,
        is_active = TRUE;
  `);

  await client.query(`
    INSERT IGNORE INTO suppliers (id, tenant_id, name, contact_person, email, phone, address, lead_time_days, created_at)
    VALUES (
        'aa111111-1111-1111-1111-111111111101',
        '00000000-0000-0000-0000-000000000001',
        'Ethiopian Pharmaceuticals Supply Service (EPSS)',
        'Yonas Bekele',
        'orders@epss.gov.et',
        '+251 11 275 8000',
        'Addis Ababa, Ethiopia',
        2,
        NOW()
    );
  `);

  await client.query(`
    INSERT IGNORE INTO drug_catalog (id, tenant_id, generic_name, brand_name, strength, dosage_form, route, atc_code, barcode, package_size, reorder_level, max_stock, default_unit_cost, default_selling_price, created_at)
    VALUES
        ('bb111111-1111-1111-1111-111111111101', '00000000-0000-0000-0000-000000000001', 'Metformin HCl', 'Glucophage', '500 mg', 'tablet', 'oral', 'A10BA02', '628100100101', '100 tablets', 50, 500, 3.50, 6.00, NOW()),
        ('bb111111-1111-1111-1111-111111111102', '00000000-0000-0000-0000-000000000001', 'Lisinopril', 'Zestril', '20 mg', 'tablet', 'oral', 'C09AA03', '628100100102', '30 tablets', 40, 300, 4.20, 7.50, NOW()),
        ('bb111111-1111-1111-1111-111111111103', '00000000-0000-0000-0000-000000000001', 'Atorvastatin Calcium', 'Lipitor', '20 mg', 'tablet', 'oral', 'C10AA05', '628100100103', '30 tablets', 30, 250, 8.00, 14.00, NOW()),
        ('bb111111-1111-1111-1111-111111111104', '00000000-0000-0000-0000-000000000001', 'Ceftriaxone Sodium', 'Rocephin', '1 g', 'injection', 'iv', 'J01DD04', '628100100104', '1 vial', 20, 150, 35.00, 55.00, NOW()),
        ('bb111111-1111-1111-1111-111111111105', '00000000-0000-0000-0000-000000000001', 'Azithromycin', 'Zithromax', '500 mg', 'tablet', 'oral', 'J01FA10', '628100100105', '3 tablets', 25, 200, 22.00, 38.00, NOW());
  `);

  await client.query(`
    INSERT IGNORE INTO subscription_plans (id, tenant_id, name, slug, description, type, billing_cycle, base_price, currency, max_members, included_services, created_at)
    VALUES
        ('55555555-5555-5555-5555-555555555501', '00000000-0000-0000-0000-000000000001', 'Comprehensive Individual Care', 'individual-standard', 'Unlimited CDSS telemedicine and chronic monitoring', 'individual', 'monthly', 1200, 'ETB', 1, '{"consultations": 4, "labTests": 2, "discountPercent": 15}', NOW()),
        ('55555555-5555-5555-5555-555555555502', '00000000-0000-0000-0000-000000000001', 'Multidisciplinary Family Shield', 'family-premium', 'Covers up to 6 family members with chronic care management', 'family', 'monthly', 2800, 'ETB', 6, '{"consultations": 12, "labTests": 6, "discountPercent": 25}', NOW());
  `);

  await client.query(`
    INSERT IGNORE INTO external_providers (id, organization_id, name, specialty, facility_name, email, phone, fhir_endpoint, preferred_transport, created_at)
    VALUES
        ('77777777-7777-7777-7777-777777777701', '00000000-0000-0000-0000-000000000001', 'Addis Kidney & Renal Care Institute', 'Nephrology & Dialysis', 'Addis Renal Tower', 'referrals@addisrenal.org', '+251 11 654 3210', 'https://fhir.addisrenal.org/r4', 'fhir', NOW()),
        ('77777777-7777-7777-7777-777777777702', '00000000-0000-0000-0000-000000000001', 'Capital Advanced Cardiology Center', 'Interventional Cardiology', 'Capital Heart Pavilion', 'triage@capitalcardio.et', '+251 11 654 3211', 'https://fhir.capitalcardio.et/r4', 'fhir', NOW());
  `);

  await client.query(`
    INSERT IGNORE INTO cases (id, case_id, case_number, tenant_id, status, chief_complaint, severity, assigned_handler_id, assigned_handler_name, assigned_role, personal, complaint, history, symptoms, ai_summary, ai_analysis, handler_notes, timeline, submitted_at, created_at, updated_at)
    VALUES
    (
      'cc000000-0000-0000-0000-000000000001',
      'CASE-2026-INIT01',
      'CASE-2026-INIT01',
      '00000000-0000-0000-0000-000000000001',
      'under_review',
      'Recurrent chest tightness and exertion dyspnea for 1 week',
      'severe',
      '00000000-0000-0000-0000-000000000099',
      'System Super Administrator',
      'physician',
      '{"fullName": "Abebe Kebede", "email": "abebe.kebede@example.com", "phone": "+251 91 123 4567", "gender": "male", "dateOfBirth": "1978-04-12", "mrn": "MRN-10023"}',
      '{"chiefComplaint": "Recurrent chest tightness and exertion dyspnea for 1 week", "severity": "severe", "duration": "1 week", "onset": "gradual", "seekingUrgent": true}',
      '{"chronicConditions": "Hypertension, Hyperlipidemia", "currentMedications": "Amlodipine 5mg, Atorvastatin 20mg", "knownAllergies": "Penicillin"}',
      '{"painScale": 6, "selectedCategories": ["cardiac", "breathing"]}',
      'Patient presents with progressive exertional dyspnea and retrosternal chest pressure. Known cardiovascular risk factors. Urgent ECG and cardiac enzyme evaluation recommended.',
      '{"urgencyLevel": "urgent", "analysisConfidence": 92, "potentialCauses": ["Unstable Angina", "Coronary Artery Disease", "GERD with esophageal spasm"]}',
      '[{"note": "Initial clinical triage completed. Case prioritized for cardiology consultation.", "author": "Dr. Sarah Mitchell", "timestamp": "2026-09-01T08:00:00Z"}]',
      '[{"event": "Case submitted by patient", "time": "2026-09-01T07:30:00Z", "actor": "Patient"}, {"event": "AI clinical analysis complete", "time": "2026-09-01T07:31:00Z", "actor": "AI Engine"}]',
      CURRENT_TIMESTAMP,
      NOW(),
      NOW()
    );
  `);

  // Legacy HR seed rows reference these stable system-user IDs.
  await client.query(`
    INSERT IGNORE INTO users (id, organization_id, email, password_hash, full_name, role, is_active, created_at, updated_at)
    VALUES
        ('11111111-1111-1111-1111-111111111101', '00000000-0000-0000-0000-000000000001', 'legacy.staff.001@Ninimed.org', SHA2('123456', 256), 'Legacy Staff 001', 'staff', TRUE, NOW(), NOW()),
        ('11111111-1111-1111-1111-111111111102', '00000000-0000-0000-0000-000000000001', 'legacy.staff.002@Ninimed.org', SHA2('123456', 256), 'Legacy Staff 002', 'staff', TRUE, NOW(), NOW()),
        ('11111111-1111-1111-1111-111111111103', '00000000-0000-0000-0000-000000000001', 'legacy.staff.003@Ninimed.org', SHA2('123456', 256), 'Legacy Staff 003', 'staff', TRUE, NOW(), NOW()),
        ('11111111-1111-1111-1111-111111111104', '00000000-0000-0000-0000-000000000001', 'legacy.staff.004@Ninimed.org', SHA2('123456', 256), 'Legacy Staff 004', 'staff', TRUE, NOW(), NOW()),
        ('11111111-1111-1111-1111-111111111105', '00000000-0000-0000-0000-000000000001', 'legacy.staff.005@Ninimed.org', SHA2('123456', 256), 'Legacy Staff 005', 'staff', TRUE, NOW(), NOW()),
        ('11111111-1111-1111-1111-111111111106', '00000000-0000-0000-0000-000000000001', 'legacy.staff.006@Ninimed.org', SHA2('123456', 256), 'Legacy Staff 006', 'staff', TRUE, NOW(), NOW()),
        ('11111111-1111-1111-1111-111111111107', '00000000-0000-0000-0000-000000000001', 'legacy.staff.007@Ninimed.org', SHA2('123456', 256), 'Legacy Staff 007', 'staff', TRUE, NOW(), NOW()),
        ('11111111-1111-1111-1111-111111111108', '00000000-0000-0000-0000-000000000001', 'legacy.staff.008@Ninimed.org', SHA2('123456', 256), 'Legacy Staff 008', 'staff', TRUE, NOW(), NOW()),
        ('11111111-1111-1111-1111-111111111109', '00000000-0000-0000-0000-000000000001', 'legacy.staff.009@Ninimed.org', SHA2('123456', 256), 'Legacy Staff 009', 'staff', TRUE, NOW(), NOW()),
        ('5c254614-7cb0-4e72-a7cb-7bbe0a98c42d', '00000000-0000-0000-0000-000000000001', 'legacy.staff.010@Ninimed.org', SHA2('123456', 256), 'Legacy Staff 010', 'staff', TRUE, NOW(), NOW());
  `);

  // Seed Staff Profiles for core clinical and administrative staff
  await client.query(`
    INSERT IGNORE INTO staff_profiles (
      id, user_id, tenant_id, employee_code, department, designation, specialization,
      license_number, license_expiry_date, cme_points, employment_type,
      base_salary_etb, on_call_allowance_rate, status, hired_at, created_at, updated_at
    ) VALUES
      ('a1111111-0001-0000-0000-000000000001', '11111111-1111-1111-1111-111111111101', '00000000-0000-0000-0000-000000000001', 'EMP-001', 'Internal Medicine', 'Lead Attending Physician & Internist', 'Internal Medicine & Cardiology', 'MD-ET-2018-0941', '2026-12-31', 48, 'full_time', 42000.00, 1500.00, 'active', '2021-01-15', NOW(), NOW()),
      ('a1111111-0001-0000-0000-000000000002', '11111111-1111-1111-1111-111111111102', '00000000-0000-0000-0000-000000000001', 'EMP-002', 'Advanced Primary Care', 'Family Nurse Practitioner (DNP)', 'Primary Care & Preventive Medicine', 'NP-ET-2020-1120', '2027-06-30', 34, 'full_time', 28500.00, 900.00, 'active', '2021-06-01', NOW(), NOW()),
      ('a1111111-0001-0000-0000-000000000003', '11111111-1111-1111-1111-111111111103', '00000000-0000-0000-0000-000000000001', 'EMP-003', 'Emergency', 'Head Nurse & Triage Supervisor', 'Emergency & Critical Care Nursing', 'RN-ET-2019-3829', '2027-01-15', 26, 'full_time', 22000.00, 800.00, 'active', '2020-03-10', NOW(), NOW()),
      ('a1111111-0001-0000-0000-000000000004', '11111111-1111-1111-1111-111111111104', '00000000-0000-0000-0000-000000000001', 'EMP-004', 'Pharmacy', 'Chief Clinical Pharmacist & Toxicologist', 'Clinical Pharmacogenomics', 'PH-ET-2017-4821', '2026-11-30', 40, 'full_time', 29000.00, 750.00, 'active', '2019-09-01', NOW(), NOW()),
      ('a1111111-0001-0000-0000-000000000005', '11111111-1111-1111-1111-111111111105', '00000000-0000-0000-0000-000000000001', 'EMP-005', 'Cardiopulmonary Rehabilitation', 'Doctor of Physical Therapy (DPT)', 'Cardiopulmonary Rehabilitation', 'PT-ET-2021-0029', '2026-10-15', 30, 'full_time', 26000.00, 600.00, 'active', '2022-02-01', NOW(), NOW()),
      ('a1111111-0001-0000-0000-000000000006', '11111111-1111-1111-1111-111111111106', '00000000-0000-0000-0000-000000000001', 'EMP-006', 'Nutrition', 'Lead Medical Nutrition Specialist', 'Diabetic Dietetics', 'DT-ET-2022-5501', '2027-08-20', 22, 'full_time', 23500.00, 500.00, 'active', '2022-05-15', NOW(), NOW()),
      ('a1111111-0001-0000-0000-000000000007', '11111111-1111-1111-1111-111111111107', '00000000-0000-0000-0000-000000000001', 'EMP-007', 'Social Work', 'Senior Clinical Social Worker & SDOH Lead', 'Medical Social Work', 'SW-ET-2020-8812', '2027-03-31', 18, 'full_time', 21000.00, 400.00, 'active', '2021-08-20', NOW(), NOW()),
      ('a1111111-0001-0000-0000-000000000008', '11111111-1111-1111-1111-111111111108', '00000000-0000-0000-0000-000000000001', 'EMP-008', 'Laboratory', 'Senior Molecular Biologist & Lab Director', 'Molecular Genomics', 'LB-ET-2018-7744', '2026-09-30', 52, 'full_time', 38000.00, 1200.00, 'active', '2020-01-10', NOW(), NOW()),
      ('a1111111-0001-0000-0000-000000000009', '11111111-1111-1111-1111-111111111109', '00000000-0000-0000-0000-000000000001', 'EMP-009', 'Clinical Operations', 'Hospital Operations Administrator', 'Health Systems Administration', 'HA-ET-2016-1002', '2028-12-31', 35, 'full_time', 35000.00, 1000.00, 'active', '2018-11-01', NOW(), NOW()),
      ('a1111111-0001-0000-0000-000000000010', '5c254614-7cb0-4e72-a7cb-7bbe0a98c42d', '00000000-0000-0000-0000-000000000001', 'EMP-010', 'System Administration', 'Chief Medical Systems Administrator', 'Clinical Informatics', 'IT-ET-2022-9900', '2029-01-01', 60, 'full_time', 45000.00, 1500.00, 'active', '2020-01-01', NOW(), NOW());
  `);
}

export async function syncComprehensiveCatalogues(client: Pool) {
  try {
    console.log("⚡ Synchronizing Intensive Laboratory Protocols...");
    for (const lab of LABORATORY_PROTOCOLS_CATALOGUE) {
      const serviceCode = `LAB_${lab.testCode.replace(/[\/\s-]/g, "_")}`;
      const desc = `Specimen: ${lab.specimen} (${lab.tubeContainer}). Ref: ${lab.referenceRangeAdult}${lab.criticalValues ? " | Critical: " + lab.criticalValues : ""}`;
      const fullName = `${lab.testName} (${lab.testCode})`;
      const metadataJson = JSON.stringify({
        testCode: lab.testCode,
        testName: lab.testName,
        specimen: lab.specimen,
        tubeContainer: lab.tubeContainer,
        collectionProtocol: lab.collectionProtocol,
        handlingStorage: lab.handlingStorage,
        referenceRangeAdult: lab.referenceRangeAdult,
        criticalValues: lab.criticalValues,
        turnaroundTime: lab.turnaroundTime,
        methodology: lab.methodology,
        category: lab.category,
        priceEtb: lab.priceEtb,
        isStatAvailable: lab.isStatAvailable || false,
      });
      const itemsJson = JSON.stringify([
        `Specimen: ${lab.specimen}`,
        `Container: ${lab.tubeContainer}`,
        `Collection: ${lab.collectionProtocol}`,
        `Storage: ${lab.handlingStorage}`,
        `Turnaround: ${lab.turnaroundTime}`,
        `Methodology: ${lab.methodology}`,
        lab.criticalValues ? `Critical Alert: ${lab.criticalValues}` : "No critical limits specified",
      ]);

      await client.query(
        `INSERT INTO service_pricing_catalog (
            id, service_code, category, name, description, base_price, currency, is_free, is_active, updated_at
        ) VALUES (
            UUID(), ?, 'laboratory', ?, ?, ?, 'ETB', FALSE, TRUE, NOW()
        )
        ON DUPLICATE KEY UPDATE
            name = VALUES(name),
            description = VALUES(description),
            base_price = VALUES(base_price),
            is_active = TRUE`,
        [serviceCode, fullName, desc, lab.priceEtb]
      );

      await client.query(
        `INSERT INTO clinical_catalog_protocols (
            id, tenant_id, kind, department_id, name, indication, items, metadata, is_active, created_at, updated_at
        ) VALUES (
            UUID(), '00000000-0000-0000-0000-000000000001', 'protocol', 'laboratory', ?, ?, ?, ?, TRUE, NOW(), NOW()
        )
        ON DUPLICATE KEY UPDATE
            indication = VALUES(indication),
            items = VALUES(items),
            metadata = VALUES(metadata),
            is_active = TRUE`,
        [fullName, "Diagnostic protocol for " + lab.testName + " (" + lab.category + "). Specimen: " + lab.specimen, itemsJson, metadataJson]
      );
    }

    console.log("⚡ Synchronizing Master Pharmacy Catalogue Items...");
    for (const item of PHARMACY_MASTER_CATALOGUE) {
      const barcode = "628" + item.drugCode.replace(/[^0-9]/g, "").padStart(9, "0");
      const unitCost = Number((item.priceEtb * 0.65).toFixed(2));
      const sellingPrice = Number(item.priceEtb.toFixed(2));
      const maxStock = item.reorderLevel * 4;

      await client.query(
        `INSERT INTO drug_catalog (
            id, tenant_id, generic_name, brand_name, strength, dosage_form, route,
            atc_code, barcode, package_size, reorder_level, max_stock,
            default_unit_cost, default_selling_price, storage_condition,
            item_code, category, section_number, section_name, is_controlled, rx_otc, is_active, created_at, updated_at
        ) VALUES (
            UUID(), '00000000-0000-0000-0000-000000000001', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, TRUE, NOW(), NOW()
        )
        ON DUPLICATE KEY UPDATE
            generic_name = VALUES(generic_name),
            brand_name = VALUES(brand_name),
            strength = VALUES(strength),
            dosage_form = VALUES(dosage_form),
            route = VALUES(route),
            category = VALUES(category),
            section_number = VALUES(section_number),
            section_name = VALUES(section_name),
            is_controlled = VALUES(is_controlled),
            rx_otc = VALUES(rx_otc),
            default_selling_price = VALUES(default_selling_price),
            reorder_level = VALUES(reorder_level),
            is_active = TRUE`,
        [
          item.genericName,
          item.brandName,
          item.strength,
          item.form,
          item.route,
          item.atcCode || item.drugCode,
          barcode,
          item.reorderUnit || "unit",
          item.reorderLevel,
          maxStock,
          unitCost,
          sellingPrice,
          item.storageCondition || "ambient",
          item.drugCode,
          item.category,
          item.sectionNumber,
          item.sectionName,
          item.isControlled,
          item.rxOtc,
        ]
      );
    }

    console.log("✅ Synchronized pharmacy and laboratory catalogues.");
  } catch (err: any) {
    console.warn("Catalog synchronization notice:", err?.message || err);
  }
}
